return {
  digraphs = {
    { char = '¡', digraph = '!I', name = 'INVERTED EXCLAMATION MARK' },
    { char = '¢', digraph = 'Ct', name = 'CENT SIGN' },
    { char = '£', digraph = 'Pd', name = 'POUND SIGN' },
    { char = '¤', digraph = 'Cu', name = 'CURRENCY SIGN' },
    { char = '¥', digraph = 'Ye', name = 'YEN SIGN' },
    { char = '¦', digraph = 'BB', name = 'BROKEN BAR' },
    { char = '§', digraph = 'SE', name = 'SECTION SIGN' },
    { char = '¨', digraph = '\':', name = 'DIAERESIS' },
    { char = '©', digraph = 'Co', name = 'COPYRIGHT SIGN' },
    { char = 'ª', digraph = '-a', name = 'FEMININE ORDINAL INDICATOR' },
    { char = '«', digraph = '<<', name = 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK' },
    { char = '¬', digraph = 'NO', name = 'NOT SIGN' },
    { char = '­', digraph = '--', name = 'SOFT HYPHEN' },
    { char = '®', digraph = 'Rg', name = 'REGISTERED SIGN' },
    { char = '¯', digraph = '\'m', name = 'MACRON' },
    { char = '°', digraph = 'DG', name = 'DEGREE SIGN' },
    { char = '±', digraph = '+-', name = 'PLUS-MINUS SIGN' },
    { char = '²', digraph = '2S', name = 'SUPERSCRIPT TWO' },
    { char = '³', digraph = '3S', name = 'SUPERSCRIPT THREE' },
    { char = '´', digraph = '\'\'', name = 'ACUTE ACCENT' },
    { char = 'µ', digraph = 'My', name = 'MICRO SIGN' },
    { char = '¶', digraph = 'PI', name = 'PILCROW SIGN' },
    { char = '·', digraph = '.M', name = 'MIDDLE DOT' },
    { char = '¸', digraph = '\',', name = 'CEDILLA' },
    { char = '¹', digraph = '1S', name = 'SUPERSCRIPT ONE' },
    { char = 'º', digraph = '-o', name = 'MASCULINE ORDINAL INDICATOR' },
    { char = '»', digraph = '>>', name = 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK' },
    { char = '¼', digraph = '14', name = 'VULGAR FRACTION ONE QUARTER' },
    { char = '½', digraph = '12', name = 'VULGAR FRACTION ONE HALF' },
    { char = '¾', digraph = '34', name = 'VULGAR FRACTION THREE QUARTERS' },
    { char = '¿', digraph = '?I', name = 'INVERTED QUESTION MARK' },
    { char = 'À', digraph = 'A!', name = 'LATIN CAPITAL LETTER A WITH GRAVE' },
    { char = 'Á', digraph = 'A\'', name = 'LATIN CAPITAL LETTER A WITH ACUTE' },
    { char = 'Â', digraph = 'A>', name = 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX' },
    { char = 'Ã', digraph = 'A?', name = 'LATIN CAPITAL LETTER A WITH TILDE' },
    { char = 'Ä', digraph = 'A:', name = 'LATIN CAPITAL LETTER A WITH DIAERESIS' },
    { char = 'Å', digraph = 'AA', name = 'LATIN CAPITAL LETTER A WITH RING ABOVE' },
    { char = 'Æ', digraph = 'AE', name = 'LATIN CAPITAL LETTER AE' },
    { char = 'Ç', digraph = 'C,', name = 'LATIN CAPITAL LETTER C WITH CEDILLA' },
    { char = 'È', digraph = 'E!', name = 'LATIN CAPITAL LETTER E WITH GRAVE' },
    { char = 'É', digraph = 'E\'', name = 'LATIN CAPITAL LETTER E WITH ACUTE' },
    { char = 'Ê', digraph = 'E>', name = 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX' },
    { char = 'Ë', digraph = 'E:', name = 'LATIN CAPITAL LETTER E WITH DIAERESIS' },
    { char = 'Ì', digraph = 'I!', name = 'LATIN CAPITAL LETTER I WITH GRAVE' },
    { char = 'Í', digraph = 'I\'', name = 'LATIN CAPITAL LETTER I WITH ACUTE' },
    { char = 'Î', digraph = 'I>', name = 'LATIN CAPITAL LETTER I WITH CIRCUMFLEX' },
    { char = 'Ï', digraph = 'I:', name = 'LATIN CAPITAL LETTER I WITH DIAERESIS' },
    { char = 'Ð', digraph = 'D-', name = 'LATIN CAPITAL LETTER ETH (Icelandic)' },
    { char = 'Ñ', digraph = 'N?', name = 'LATIN CAPITAL LETTER N WITH TILDE' },
    { char = 'Ò', digraph = 'O!', name = 'LATIN CAPITAL LETTER O WITH GRAVE' },
    { char = 'Ó', digraph = 'O\'', name = 'LATIN CAPITAL LETTER O WITH ACUTE' },
    { char = 'Ô', digraph = 'O>', name = 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX' },
    { char = 'Õ', digraph = 'O?', name = 'LATIN CAPITAL LETTER O WITH TILDE' },
    { char = 'Ö', digraph = 'O:', name = 'LATIN CAPITAL LETTER O WITH DIAERESIS' },
    { char = '×', digraph = '*X', name = 'MULTIPLICATION SIGN' },
    { char = 'Ø', digraph = 'O/', name = 'LATIN CAPITAL LETTER O WITH STROKE' },
    { char = 'Ù', digraph = 'U!', name = 'LATIN CAPITAL LETTER U WITH GRAVE' },
    { char = 'Ú', digraph = 'U\'', name = 'LATIN CAPITAL LETTER U WITH ACUTE' },
    { char = 'Û', digraph = 'U>', name = 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX' },
    { char = 'Ü', digraph = 'U:', name = 'LATIN CAPITAL LETTER U WITH DIAERESIS' },
    { char = 'Ý', digraph = 'Y\'', name = 'LATIN CAPITAL LETTER Y WITH ACUTE' },
    { char = 'Þ', digraph = 'TH', name = 'LATIN CAPITAL LETTER THORN (Icelandic)' },
    { char = 'ß', digraph = 'ss', name = 'LATIN SMALL LETTER SHARP S (German)' },
    { char = 'à', digraph = 'a!', name = 'LATIN SMALL LETTER A WITH GRAVE' },
    { char = 'á', digraph = 'a\'', name = 'LATIN SMALL LETTER A WITH ACUTE' },
    { char = 'â', digraph = 'a>', name = 'LATIN SMALL LETTER A WITH CIRCUMFLEX' },
    { char = 'ã', digraph = 'a?', name = 'LATIN SMALL LETTER A WITH TILDE' },
    { char = 'ä', digraph = 'a:', name = 'LATIN SMALL LETTER A WITH DIAERESIS' },
    { char = 'å', digraph = 'aa', name = 'LATIN SMALL LETTER A WITH RING ABOVE' },
    { char = 'æ', digraph = 'ae', name = 'LATIN SMALL LETTER AE' },
    { char = 'ç', digraph = 'c,', name = 'LATIN SMALL LETTER C WITH CEDILLA' },
    { char = 'è', digraph = 'e!', name = 'LATIN SMALL LETTER E WITH GRAVE' },
    { char = 'é', digraph = 'e\'', name = 'LATIN SMALL LETTER E WITH ACUTE' },
    { char = 'ê', digraph = 'e>', name = 'LATIN SMALL LETTER E WITH CIRCUMFLEX' },
    { char = 'ë', digraph = 'e:', name = 'LATIN SMALL LETTER E WITH DIAERESIS' },
    { char = 'ì', digraph = 'i!', name = 'LATIN SMALL LETTER I WITH GRAVE' },
    { char = 'í', digraph = 'i\'', name = 'LATIN SMALL LETTER I WITH ACUTE' },
    { char = 'î', digraph = 'i>', name = 'LATIN SMALL LETTER I WITH CIRCUMFLEX' },
    { char = 'ï', digraph = 'i:', name = 'LATIN SMALL LETTER I WITH DIAERESIS' },
    { char = 'ð', digraph = 'd-', name = 'LATIN SMALL LETTER ETH (Icelandic)' },
    { char = 'ñ', digraph = 'n?', name = 'LATIN SMALL LETTER N WITH TILDE' },
    { char = 'ò', digraph = 'o!', name = 'LATIN SMALL LETTER O WITH GRAVE' },
    { char = 'ó', digraph = 'o\'', name = 'LATIN SMALL LETTER O WITH ACUTE' },
    { char = 'ô', digraph = 'o>', name = 'LATIN SMALL LETTER O WITH CIRCUMFLEX' },
    { char = 'õ', digraph = 'o?', name = 'LATIN SMALL LETTER O WITH TILDE' },
    { char = 'ö', digraph = 'o:', name = 'LATIN SMALL LETTER O WITH DIAERESIS' },
    { char = '÷', digraph = '-:', name = 'DIVISION SIGN' },
    { char = 'ø', digraph = 'o/', name = 'LATIN SMALL LETTER O WITH STROKE' },
    { char = 'ù', digraph = 'u!', name = 'LATIN SMALL LETTER U WITH GRAVE' },
    { char = 'ú', digraph = 'u\'', name = 'LATIN SMALL LETTER U WITH ACUTE' },
    { char = 'û', digraph = 'u>', name = 'LATIN SMALL LETTER U WITH CIRCUMFLEX' },
    { char = 'ü', digraph = 'u:', name = 'LATIN SMALL LETTER U WITH DIAERESIS' },
    { char = 'ý', digraph = 'y\'', name = 'LATIN SMALL LETTER Y WITH ACUTE' },
    { char = 'þ', digraph = 'th', name = 'LATIN SMALL LETTER THORN (Icelandic)' },
    { char = 'ÿ', digraph = 'y:', name = 'LATIN SMALL LETTER Y WITH DIAERESIS' },
    { char = 'Ā', digraph = 'A-', name = 'LATIN CAPITAL LETTER A WITH MACRON' },
    { char = 'ā', digraph = 'a-', name = 'LATIN SMALL LETTER A WITH MACRON' },
    { char = 'Ă', digraph = 'A(', name = 'LATIN CAPITAL LETTER A WITH BREVE' },
    { char = 'ă', digraph = 'a(', name = 'LATIN SMALL LETTER A WITH BREVE' },
    { char = 'Ą', digraph = 'A;', name = 'LATIN CAPITAL LETTER A WITH OGONEK' },
    { char = 'ą', digraph = 'a;', name = 'LATIN SMALL LETTER A WITH OGONEK' },
    { char = 'Ć', digraph = 'C\'', name = 'LATIN CAPITAL LETTER C WITH ACUTE' },
    { char = 'ć', digraph = 'c\'', name = 'LATIN SMALL LETTER C WITH ACUTE' },
    { char = 'Ĉ', digraph = 'C>', name = 'LATIN CAPITAL LETTER C WITH CIRCUMFLEX' },
    { char = 'ĉ', digraph = 'c>', name = 'LATIN SMALL LETTER C WITH CIRCUMFLEX' },
    { char = 'Ċ', digraph = 'C.', name = 'LATIN CAPITAL LETTER C WITH DOT ABOVE' },
    { char = 'ċ', digraph = 'c.', name = 'LATIN SMALL LETTER C WITH DOT ABOVE' },
    { char = 'Č', digraph = 'C<', name = 'LATIN CAPITAL LETTER C WITH CARON' },
    { char = 'č', digraph = 'c<', name = 'LATIN SMALL LETTER C WITH CARON' },
    { char = 'Ď', digraph = 'D<', name = 'LATIN CAPITAL LETTER D WITH CARON' },
    { char = 'ď', digraph = 'd<', name = 'LATIN SMALL LETTER D WITH CARON' },
    { char = 'Đ', digraph = 'D/', name = 'LATIN CAPITAL LETTER D WITH STROKE' },
    { char = 'đ', digraph = 'd/', name = 'LATIN SMALL LETTER D WITH STROKE' },
    { char = 'Ē', digraph = 'E-', name = 'LATIN CAPITAL LETTER E WITH MACRON' },
    { char = 'ē', digraph = 'e-', name = 'LATIN SMALL LETTER E WITH MACRON' },
    { char = 'Ĕ', digraph = 'E(', name = 'LATIN CAPITAL LETTER E WITH BREVE' },
    { char = 'ĕ', digraph = 'e(', name = 'LATIN SMALL LETTER E WITH BREVE' },
    { char = 'Ė', digraph = 'E.', name = 'LATIN CAPITAL LETTER E WITH DOT ABOVE' },
    { char = 'ė', digraph = 'e.', name = 'LATIN SMALL LETTER E WITH DOT ABOVE' },
    { char = 'Ę', digraph = 'E;', name = 'LATIN CAPITAL LETTER E WITH OGONEK' },
    { char = 'ę', digraph = 'e;', name = 'LATIN SMALL LETTER E WITH OGONEK' },
    { char = 'Ě', digraph = 'E<', name = 'LATIN CAPITAL LETTER E WITH CARON' },
    { char = 'ě', digraph = 'e<', name = 'LATIN SMALL LETTER E WITH CARON' },
    { char = 'Ĝ', digraph = 'G>', name = 'LATIN CAPITAL LETTER G WITH CIRCUMFLEX' },
    { char = 'ĝ', digraph = 'g>', name = 'LATIN SMALL LETTER G WITH CIRCUMFLEX' },
    { char = 'Ğ', digraph = 'G(', name = 'LATIN CAPITAL LETTER G WITH BREVE' },
    { char = 'ğ', digraph = 'g(', name = 'LATIN SMALL LETTER G WITH BREVE' },
    { char = 'Ġ', digraph = 'G.', name = 'LATIN CAPITAL LETTER G WITH DOT ABOVE' },
    { char = 'ġ', digraph = 'g.', name = 'LATIN SMALL LETTER G WITH DOT ABOVE' },
    { char = 'Ģ', digraph = 'G,', name = 'LATIN CAPITAL LETTER G WITH CEDILLA' },
    { char = 'ģ', digraph = 'g,', name = 'LATIN SMALL LETTER G WITH CEDILLA' },
    { char = 'Ĥ', digraph = 'H>', name = 'LATIN CAPITAL LETTER H WITH CIRCUMFLEX' },
    { char = 'ĥ', digraph = 'h>', name = 'LATIN SMALL LETTER H WITH CIRCUMFLEX' },
    { char = 'Ħ', digraph = 'H/', name = 'LATIN CAPITAL LETTER H WITH STROKE' },
    { char = 'ħ', digraph = 'h/', name = 'LATIN SMALL LETTER H WITH STROKE' },
    { char = 'Ĩ', digraph = 'I?', name = 'LATIN CAPITAL LETTER I WITH TILDE' },
    { char = 'ĩ', digraph = 'i?', name = 'LATIN SMALL LETTER I WITH TILDE' },
    { char = 'Ī', digraph = 'I-', name = 'LATIN CAPITAL LETTER I WITH MACRON' },
    { char = 'ī', digraph = 'i-', name = 'LATIN SMALL LETTER I WITH MACRON' },
    { char = 'Ĭ', digraph = 'I(', name = 'LATIN CAPITAL LETTER I WITH BREVE' },
    { char = 'ĭ', digraph = 'i(', name = 'LATIN SMALL LETTER I WITH BREVE' },
    { char = 'Į', digraph = 'I;', name = 'LATIN CAPITAL LETTER I WITH OGONEK' },
    { char = 'į', digraph = 'i;', name = 'LATIN SMALL LETTER I WITH OGONEK' },
    { char = 'İ', digraph = 'I.', name = 'LATIN CAPITAL LETTER I WITH DOT ABOVE' },
    { char = 'ı', digraph = 'i.', name = 'LATIN SMALL LETTER DOTLESS I' },
    { char = 'Ĳ', digraph = 'IJ', name = 'LATIN CAPITAL LIGATURE IJ' },
    { char = 'ĳ', digraph = 'ij', name = 'LATIN SMALL LIGATURE IJ' },
    { char = 'Ĵ', digraph = 'J>', name = 'LATIN CAPITAL LETTER J WITH CIRCUMFLEX' },
    { char = 'ĵ', digraph = 'j>', name = 'LATIN SMALL LETTER J WITH CIRCUMFLEX' },
    { char = 'Ķ', digraph = 'K,', name = 'LATIN CAPITAL LETTER K WITH CEDILLA' },
    { char = 'ķ', digraph = 'k,', name = 'LATIN SMALL LETTER K WITH CEDILLA' },
    { char = 'ĸ', digraph = 'kk', name = 'LATIN SMALL LETTER KRA' },
    { char = 'Ĺ', digraph = 'L\'', name = 'LATIN CAPITAL LETTER L WITH ACUTE' },
    { char = 'ĺ', digraph = 'l\'', name = 'LATIN SMALL LETTER L WITH ACUTE' },
    { char = 'Ļ', digraph = 'L,', name = 'LATIN CAPITAL LETTER L WITH CEDILLA' },
    { char = 'ļ', digraph = 'l,', name = 'LATIN SMALL LETTER L WITH CEDILLA' },
    { char = 'Ľ', digraph = 'L<', name = 'LATIN CAPITAL LETTER L WITH CARON' },
    { char = 'ľ', digraph = 'l<', name = 'LATIN SMALL LETTER L WITH CARON' },
    { char = 'Ŀ', digraph = 'L.', name = 'LATIN CAPITAL LETTER L WITH MIDDLE DOT' },
    { char = 'ŀ', digraph = 'l.', name = 'LATIN SMALL LETTER L WITH MIDDLE DOT' },
    { char = 'Ł', digraph = 'L/', name = 'LATIN CAPITAL LETTER L WITH STROKE' },
    { char = 'ł', digraph = 'l/', name = 'LATIN SMALL LETTER L WITH STROKE' },
    { char = 'Ń', digraph = 'N\'', name = 'LATIN CAPITAL LETTER N WITH ACUTE `' },
    { char = 'ń', digraph = 'n\'', name = 'LATIN SMALL LETTER N WITH ACUTE `' },
    { char = 'Ņ', digraph = 'N,', name = 'LATIN CAPITAL LETTER N WITH CEDILLA `' },
    { char = 'ņ', digraph = 'n,', name = 'LATIN SMALL LETTER N WITH CEDILLA `' },
    { char = 'Ň', digraph = 'N<', name = 'LATIN CAPITAL LETTER N WITH CARON `' },
    { char = 'ň', digraph = 'n<', name = 'LATIN SMALL LETTER N WITH CARON `' },
    { char = 'ŉ', digraph = '\'n', name = 'LATIN SMALL LETTER N PRECEDED BY APOSTROPHE `' },
    { char = 'Ŋ', digraph = 'NG', name = 'LATIN CAPITAL LETTER ENG' },
    { char = 'ŋ', digraph = 'ng', name = 'LATIN SMALL LETTER ENG' },
    { char = 'Ō', digraph = 'O-', name = 'LATIN CAPITAL LETTER O WITH MACRON' },
    { char = 'ō', digraph = 'o-', name = 'LATIN SMALL LETTER O WITH MACRON' },
    { char = 'Ŏ', digraph = 'O(', name = 'LATIN CAPITAL LETTER O WITH BREVE' },
    { char = 'ŏ', digraph = 'o(', name = 'LATIN SMALL LETTER O WITH BREVE' },
    { char = 'Ő', digraph = 'O"', name = 'LATIN CAPITAL LETTER O WITH DOUBLE ACUTE' },
    { char = 'ő', digraph = 'o"', name = 'LATIN SMALL LETTER O WITH DOUBLE ACUTE' },
    { char = 'Œ', digraph = 'OE', name = 'LATIN CAPITAL LIGATURE OE' },
    { char = 'œ', digraph = 'oe', name = 'LATIN SMALL LIGATURE OE' },
    { char = 'Ŕ', digraph = 'R\'', name = 'LATIN CAPITAL LETTER R WITH ACUTE' },
    { char = 'ŕ', digraph = 'r\'', name = 'LATIN SMALL LETTER R WITH ACUTE' },
    { char = 'Ŗ', digraph = 'R,', name = 'LATIN CAPITAL LETTER R WITH CEDILLA' },
    { char = 'ŗ', digraph = 'r,', name = 'LATIN SMALL LETTER R WITH CEDILLA' },
    { char = 'Ř', digraph = 'R<', name = 'LATIN CAPITAL LETTER R WITH CARON' },
    { char = 'ř', digraph = 'r<', name = 'LATIN SMALL LETTER R WITH CARON' },
    { char = 'Ś', digraph = 'S\'', name = 'LATIN CAPITAL LETTER S WITH ACUTE' },
    { char = 'ś', digraph = 's\'', name = 'LATIN SMALL LETTER S WITH ACUTE' },
    { char = 'Ŝ', digraph = 'S>', name = 'LATIN CAPITAL LETTER S WITH CIRCUMFLEX' },
    { char = 'ŝ', digraph = 's>', name = 'LATIN SMALL LETTER S WITH CIRCUMFLEX' },
    { char = 'Ş', digraph = 'S,', name = 'LATIN CAPITAL LETTER S WITH CEDILLA' },
    { char = 'ş', digraph = 's,', name = 'LATIN SMALL LETTER S WITH CEDILLA' },
    { char = 'Š', digraph = 'S<', name = 'LATIN CAPITAL LETTER S WITH CARON' },
    { char = 'š', digraph = 's<', name = 'LATIN SMALL LETTER S WITH CARON' },
    { char = 'Ţ', digraph = 'T,', name = 'LATIN CAPITAL LETTER T WITH CEDILLA' },
    { char = 'ţ', digraph = 't,', name = 'LATIN SMALL LETTER T WITH CEDILLA' },
    { char = 'Ť', digraph = 'T<', name = 'LATIN CAPITAL LETTER T WITH CARON' },
    { char = 'ť', digraph = 't<', name = 'LATIN SMALL LETTER T WITH CARON' },
    { char = 'Ŧ', digraph = 'T/', name = 'LATIN CAPITAL LETTER T WITH STROKE' },
    { char = 'ŧ', digraph = 't/', name = 'LATIN SMALL LETTER T WITH STROKE' },
    { char = 'Ũ', digraph = 'U?', name = 'LATIN CAPITAL LETTER U WITH TILDE' },
    { char = 'ũ', digraph = 'u?', name = 'LATIN SMALL LETTER U WITH TILDE' },
    { char = 'Ū', digraph = 'U-', name = 'LATIN CAPITAL LETTER U WITH MACRON' },
    { char = 'ū', digraph = 'u-', name = 'LATIN SMALL LETTER U WITH MACRON' },
    { char = 'Ŭ', digraph = 'U(', name = 'LATIN CAPITAL LETTER U WITH BREVE' },
    { char = 'ŭ', digraph = 'u(', name = 'LATIN SMALL LETTER U WITH BREVE' },
    { char = 'Ů', digraph = 'U0', name = 'LATIN CAPITAL LETTER U WITH RING ABOVE' },
    { char = 'ů', digraph = 'u0', name = 'LATIN SMALL LETTER U WITH RING ABOVE' },
    { char = 'Ű', digraph = 'U"', name = 'LATIN CAPITAL LETTER U WITH DOUBLE ACUTE' },
    { char = 'ű', digraph = 'u"', name = 'LATIN SMALL LETTER U WITH DOUBLE ACUTE' },
    { char = 'Ų', digraph = 'U;', name = 'LATIN CAPITAL LETTER U WITH OGONEK' },
    { char = 'ų', digraph = 'u;', name = 'LATIN SMALL LETTER U WITH OGONEK' },
    { char = 'Ŵ', digraph = 'W>', name = 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX' },
    { char = 'ŵ', digraph = 'w>', name = 'LATIN SMALL LETTER W WITH CIRCUMFLEX' },
    { char = 'Ŷ', digraph = 'Y>', name = 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX' },
    { char = 'ŷ', digraph = 'y>', name = 'LATIN SMALL LETTER Y WITH CIRCUMFLEX' },
    { char = 'Ÿ', digraph = 'Y:', name = 'LATIN CAPITAL LETTER Y WITH DIAERESIS' },
    { char = 'Ź', digraph = 'Z\'', name = 'LATIN CAPITAL LETTER Z WITH ACUTE' },
    { char = 'ź', digraph = 'z\'', name = 'LATIN SMALL LETTER Z WITH ACUTE' },
    { char = 'Ż', digraph = 'Z.', name = 'LATIN CAPITAL LETTER Z WITH DOT ABOVE' },
    { char = 'ż', digraph = 'z.', name = 'LATIN SMALL LETTER Z WITH DOT ABOVE' },
    { char = 'Ž', digraph = 'Z<', name = 'LATIN CAPITAL LETTER Z WITH CARON' },
    { char = 'ž', digraph = 'z<', name = 'LATIN SMALL LETTER Z WITH CARON' },
    { char = 'Ơ', digraph = 'O9', name = 'LATIN CAPITAL LETTER O WITH HORN' },
    { char = 'ơ', digraph = 'o9', name = 'LATIN SMALL LETTER O WITH HORN' },
    { char = 'Ƣ', digraph = 'OI', name = 'LATIN CAPITAL LETTER OI' },
    { char = 'ƣ', digraph = 'oi', name = 'LATIN SMALL LETTER OI' },
    { char = 'Ʀ', digraph = 'yr', name = 'LATIN LETTER YR' },
    { char = 'Ư', digraph = 'U9', name = 'LATIN CAPITAL LETTER U WITH HORN' },
    { char = 'ư', digraph = 'u9', name = 'LATIN SMALL LETTER U WITH HORN' },
    { char = 'Ƶ', digraph = 'Z/', name = 'LATIN CAPITAL LETTER Z WITH STROKE' },
    { char = 'ƶ', digraph = 'z/', name = 'LATIN SMALL LETTER Z WITH STROKE' },
    { char = 'Ʒ', digraph = 'ED', name = 'LATIN CAPITAL LETTER EZH' },
    { char = 'Ǎ', digraph = 'A<', name = 'LATIN CAPITAL LETTER A WITH CARON' },
    { char = 'ǎ', digraph = 'a<', name = 'LATIN SMALL LETTER A WITH CARON' },
    { char = 'Ǐ', digraph = 'I<', name = 'LATIN CAPITAL LETTER I WITH CARON' },
    { char = 'ǐ', digraph = 'i<', name = 'LATIN SMALL LETTER I WITH CARON' },
    { char = 'Ǒ', digraph = 'O<', name = 'LATIN CAPITAL LETTER O WITH CARON' },
    { char = 'ǒ', digraph = 'o<', name = 'LATIN SMALL LETTER O WITH CARON' },
    { char = 'Ǔ', digraph = 'U<', name = 'LATIN CAPITAL LETTER U WITH CARON' },
    { char = 'ǔ', digraph = 'u<', name = 'LATIN SMALL LETTER U WITH CARON' },
    { char = 'Ǟ', digraph = 'A1', name = 'LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON' },
    { char = 'ǟ', digraph = 'a1', name = 'LATIN SMALL LETTER A WITH DIAERESIS AND MACRON' },
    { char = 'Ǡ', digraph = 'A7', name = 'LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON' },
    { char = 'ǡ', digraph = 'a7', name = 'LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON' },
    { char = 'Ǣ', digraph = 'A3', name = 'LATIN CAPITAL LETTER AE WITH MACRON' },
    { char = 'ǣ', digraph = 'a3', name = 'LATIN SMALL LETTER AE WITH MACRON' },
    { char = 'Ǥ', digraph = 'G/', name = 'LATIN CAPITAL LETTER G WITH STROKE' },
    { char = 'ǥ', digraph = 'g/', name = 'LATIN SMALL LETTER G WITH STROKE' },
    { char = 'Ǧ', digraph = 'G<', name = 'LATIN CAPITAL LETTER G WITH CARON' },
    { char = 'ǧ', digraph = 'g<', name = 'LATIN SMALL LETTER G WITH CARON' },
    { char = 'Ǩ', digraph = 'K<', name = 'LATIN CAPITAL LETTER K WITH CARON' },
    { char = 'ǩ', digraph = 'k<', name = 'LATIN SMALL LETTER K WITH CARON' },
    { char = 'Ǫ', digraph = 'O;', name = 'LATIN CAPITAL LETTER O WITH OGONEK' },
    { char = 'ǫ', digraph = 'o;', name = 'LATIN SMALL LETTER O WITH OGONEK' },
    { char = 'Ǭ', digraph = 'O1', name = 'LATIN CAPITAL LETTER O WITH OGONEK AND MACRON' },
    { char = 'ǭ', digraph = 'o1', name = 'LATIN SMALL LETTER O WITH OGONEK AND MACRON' },
    { char = 'Ǯ', digraph = 'EZ', name = 'LATIN CAPITAL LETTER EZH WITH CARON' },
    { char = 'ǯ', digraph = 'ez', name = 'LATIN SMALL LETTER EZH WITH CARON' },
    { char = 'ǰ', digraph = 'j<', name = 'LATIN SMALL LETTER J WITH CARON' },
    { char = 'Ǵ', digraph = 'G\'', name = 'LATIN CAPITAL LETTER G WITH ACUTE' },
    { char = 'ǵ', digraph = 'g\'', name = 'LATIN SMALL LETTER G WITH ACUTE' },
    { char = 'ʿ', digraph = ';S', name = 'MODIFIER LETTER LEFT HALF RING' },
    { char = 'ˇ', digraph = '\'<', name = 'CARON' },
    { char = '˘', digraph = '\'(', name = 'BREVE' },
    { char = '˙', digraph = '\'.', name = 'DOT ABOVE' },
    { char = '˚', digraph = '\'0', name = 'RING ABOVE' },
    { char = '˛', digraph = '\';', name = 'OGONEK' },
    { char = '˝', digraph = '\'"', name = 'DOUBLE ACUTE ACCENT' },
    { char = 'Ά', digraph = 'A%', name = 'GREEK CAPITAL LETTER ALPHA WITH TONOS' },
    { char = 'Έ', digraph = 'E%', name = 'GREEK CAPITAL LETTER EPSILON WITH TONOS' },
    { char = 'Ή', digraph = 'Y%', name = 'GREEK CAPITAL LETTER ETA WITH TONOS' },
    { char = 'Ί', digraph = 'I%', name = 'GREEK CAPITAL LETTER IOTA WITH TONOS' },
    { char = 'Ό', digraph = 'O%', name = 'GREEK CAPITAL LETTER OMICRON WITH TONOS' },
    { char = 'Ύ', digraph = 'U%', name = 'GREEK CAPITAL LETTER UPSILON WITH TONOS' },
    { char = 'Ώ', digraph = 'W%', name = 'GREEK CAPITAL LETTER OMEGA WITH TONOS' },
    { char = 'ΐ', digraph = 'i3', name = 'GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS' },
    { char = 'Α', digraph = 'A*', name = 'GREEK CAPITAL LETTER ALPHA' },
    { char = 'Β', digraph = 'B*', name = 'GREEK CAPITAL LETTER BETA' },
    { char = 'Γ', digraph = 'G*', name = 'GREEK CAPITAL LETTER GAMMA' },
    { char = 'Δ', digraph = 'D*', name = 'GREEK CAPITAL LETTER DELTA' },
    { char = 'Ε', digraph = 'E*', name = 'GREEK CAPITAL LETTER EPSILON' },
    { char = 'Ζ', digraph = 'Z*', name = 'GREEK CAPITAL LETTER ZETA' },
    { char = 'Η', digraph = 'Y*', name = 'GREEK CAPITAL LETTER ETA' },
    { char = 'Θ', digraph = 'H*', name = 'GREEK CAPITAL LETTER THETA' },
    { char = 'Ι', digraph = 'I*', name = 'GREEK CAPITAL LETTER IOTA' },
    { char = 'Κ', digraph = 'K*', name = 'GREEK CAPITAL LETTER KAPPA' },
    { char = 'Λ', digraph = 'L*', name = 'GREEK CAPITAL LETTER LAMDA (aka LAMBDA)' },
    { char = 'Μ', digraph = 'M*', name = 'GREEK CAPITAL LETTER MU' },
    { char = 'Ν', digraph = 'N*', name = 'GREEK CAPITAL LETTER NU' },
    { char = 'Ξ', digraph = 'C*', name = 'GREEK CAPITAL LETTER XI' },
    { char = 'Ο', digraph = 'O*', name = 'GREEK CAPITAL LETTER OMICRON' },
    { char = 'Π', digraph = 'P*', name = 'GREEK CAPITAL LETTER PI' },
    { char = 'Ρ', digraph = 'R*', name = 'GREEK CAPITAL LETTER RHO' },
    { char = 'Σ', digraph = 'S*', name = 'GREEK CAPITAL LETTER SIGMA' },
    { char = 'Τ', digraph = 'T*', name = 'GREEK CAPITAL LETTER TAU' },
    { char = 'Υ', digraph = 'U*', name = 'GREEK CAPITAL LETTER UPSILON' },
    { char = 'Φ', digraph = 'F*', name = 'GREEK CAPITAL LETTER PHI' },
    { char = 'Χ', digraph = 'X*', name = 'GREEK CAPITAL LETTER CHI' },
    { char = 'Ψ', digraph = 'Q*', name = 'GREEK CAPITAL LETTER PSI' },
    { char = 'Ω', digraph = 'W*', name = 'GREEK CAPITAL LETTER OMEGA' },
    { char = 'Ϊ', digraph = 'J*', name = 'GREEK CAPITAL LETTER IOTA WITH DIALYTIKA' },
    { char = 'Ϋ', digraph = 'V*', name = 'GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA' },
    { char = 'ά', digraph = 'a%', name = 'GREEK SMALL LETTER ALPHA WITH TONOS' },
    { char = 'έ', digraph = 'e%', name = 'GREEK SMALL LETTER EPSILON WITH TONOS' },
    { char = 'ή', digraph = 'y%', name = 'GREEK SMALL LETTER ETA WITH TONOS' },
    { char = 'ί', digraph = 'i%', name = 'GREEK SMALL LETTER IOTA WITH TONOS' },
    { char = 'ΰ', digraph = 'u3', name = 'GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS' },
    { char = 'α', digraph = 'a*', name = 'GREEK SMALL LETTER ALPHA' },
    { char = 'β', digraph = 'b*', name = 'GREEK SMALL LETTER BETA' },
    { char = 'γ', digraph = 'g*', name = 'GREEK SMALL LETTER GAMMA' },
    { char = 'δ', digraph = 'd*', name = 'GREEK SMALL LETTER DELTA' },
    { char = 'ε', digraph = 'e*', name = 'GREEK SMALL LETTER EPSILON' },
    { char = 'ζ', digraph = 'z*', name = 'GREEK SMALL LETTER ZETA' },
    { char = 'η', digraph = 'y*', name = 'GREEK SMALL LETTER ETA' },
    { char = 'θ', digraph = 'h*', name = 'GREEK SMALL LETTER THETA' },
    { char = 'ι', digraph = 'i*', name = 'GREEK SMALL LETTER IOTA' },
    { char = 'κ', digraph = 'k*', name = 'GREEK SMALL LETTER KAPPA' },
    { char = 'λ', digraph = 'l*', name = 'GREEK SMALL LETTER LAMDA (aka LAMBDA)' },
    { char = 'μ', digraph = 'm*', name = 'GREEK SMALL LETTER MU' },
    { char = 'ν', digraph = 'n*', name = 'GREEK SMALL LETTER NU' },
    { char = 'ξ', digraph = 'c*', name = 'GREEK SMALL LETTER XI' },
    { char = 'ο', digraph = 'o*', name = 'GREEK SMALL LETTER OMICRON' },
    { char = 'π', digraph = 'p*', name = 'GREEK SMALL LETTER PI' },
    { char = 'ρ', digraph = 'r*', name = 'GREEK SMALL LETTER RHO' },
    { char = 'ς', digraph = '*s', name = 'GREEK SMALL LETTER FINAL SIGMA' },
    { char = 'σ', digraph = 's*', name = 'GREEK SMALL LETTER SIGMA' },
    { char = 'τ', digraph = 't*', name = 'GREEK SMALL LETTER TAU' },
    { char = 'υ', digraph = 'u*', name = 'GREEK SMALL LETTER UPSILON' },
    { char = 'φ', digraph = 'f*', name = 'GREEK SMALL LETTER PHI' },
    { char = 'χ', digraph = 'x*', name = 'GREEK SMALL LETTER CHI' },
    { char = 'ψ', digraph = 'q*', name = 'GREEK SMALL LETTER PSI' },
    { char = 'ω', digraph = 'w*', name = 'GREEK SMALL LETTER OMEGA' },
    { char = 'ϊ', digraph = 'j*', name = 'GREEK SMALL LETTER IOTA WITH DIALYTIKA' },
    { char = 'ϋ', digraph = 'v*', name = 'GREEK SMALL LETTER UPSILON WITH DIALYTIKA' },
    { char = 'ό', digraph = 'o%', name = 'GREEK SMALL LETTER OMICRON WITH TONOS' },
    { char = 'ύ', digraph = 'u%', name = 'GREEK SMALL LETTER UPSILON WITH TONOS' },
    { char = 'ώ', digraph = 'w%', name = 'GREEK SMALL LETTER OMEGA WITH TONOS' },
    { char = 'Ϙ', digraph = '\'G', name = 'GREEK LETTER ARCHAIC KOPPA' },
    { char = 'ϙ', digraph = ',G', name = 'GREEK SMALL LETTER ARCHAIC KOPPA' },
    { char = 'Ϛ', digraph = 'T3', name = 'GREEK LETTER STIGMA' },
    { char = 'ϛ', digraph = 't3', name = 'GREEK SMALL LETTER STIGMA' },
    { char = 'Ϝ', digraph = 'M3', name = 'GREEK LETTER DIGAMMA' },
    { char = 'ϝ', digraph = 'm3', name = 'GREEK SMALL LETTER DIGAMMA' },
    { char = 'Ϟ', digraph = 'K3', name = 'GREEK LETTER KOPPA' },
    { char = 'ϟ', digraph = 'k3', name = 'GREEK SMALL LETTER KOPPA' },
    { char = 'Ϡ', digraph = 'P3', name = 'GREEK LETTER SAMPI' },
    { char = 'ϡ', digraph = 'p3', name = 'GREEK SMALL LETTER SAMPI' },
    { char = 'ϴ', digraph = '\'%', name = 'GREEK CAPITAL THETA SYMBOL' },
    { char = 'ϵ', digraph = 'j3', name = 'GREEK LUNATE EPSILON SYMBOL' },
    { char = 'Ё', digraph = 'IO', name = 'CYRILLIC CAPITAL LETTER IO' },
    { char = 'Ђ', digraph = 'D%', name = 'CYRILLIC CAPITAL LETTER DJE' },
    { char = 'Ѓ', digraph = 'G%', name = 'CYRILLIC CAPITAL LETTER GJE' },
    { char = 'Є', digraph = 'IE', name = 'CYRILLIC CAPITAL LETTER UKRAINIAN IE' },
    { char = 'Ѕ', digraph = 'DS', name = 'CYRILLIC CAPITAL LETTER DZE' },
    { char = 'І', digraph = 'II', name = 'CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I' },
    { char = 'Ї', digraph = 'YI', name = 'CYRILLIC CAPITAL LETTER YI' },
    { char = 'Ј', digraph = 'J%', name = 'CYRILLIC CAPITAL LETTER JE' },
    { char = 'Љ', digraph = 'LJ', name = 'CYRILLIC CAPITAL LETTER LJE' },
    { char = 'Њ', digraph = 'NJ', name = 'CYRILLIC CAPITAL LETTER NJE' },
    { char = 'Ћ', digraph = 'Ts', name = 'CYRILLIC CAPITAL LETTER TSHE' },
    { char = 'Ќ', digraph = 'KJ', name = 'CYRILLIC CAPITAL LETTER KJE' },
    { char = 'Ў', digraph = 'V%', name = 'CYRILLIC CAPITAL LETTER SHORT U' },
    { char = 'Џ', digraph = 'DZ', name = 'CYRILLIC CAPITAL LETTER DZHE' },
    { char = 'А', digraph = 'A=', name = 'CYRILLIC CAPITAL LETTER A' },
    { char = 'Б', digraph = 'B=', name = 'CYRILLIC CAPITAL LETTER BE' },
    { char = 'В', digraph = 'V=', name = 'CYRILLIC CAPITAL LETTER VE' },
    { char = 'Г', digraph = 'G=', name = 'CYRILLIC CAPITAL LETTER GHE' },
    { char = 'Д', digraph = 'D=', name = 'CYRILLIC CAPITAL LETTER DE' },
    { char = 'Е', digraph = 'E=', name = 'CYRILLIC CAPITAL LETTER IE' },
    { char = 'Ж', digraph = 'Z%', name = 'CYRILLIC CAPITAL LETTER ZHE' },
    { char = 'З', digraph = 'Z=', name = 'CYRILLIC CAPITAL LETTER ZE' },
    { char = 'И', digraph = 'I=', name = 'CYRILLIC CAPITAL LETTER I' },
    { char = 'Й', digraph = 'J=', name = 'CYRILLIC CAPITAL LETTER SHORT I' },
    { char = 'К', digraph = 'K=', name = 'CYRILLIC CAPITAL LETTER KA' },
    { char = 'Л', digraph = 'L=', name = 'CYRILLIC CAPITAL LETTER EL' },
    { char = 'М', digraph = 'M=', name = 'CYRILLIC CAPITAL LETTER EM' },
    { char = 'Н', digraph = 'N=', name = 'CYRILLIC CAPITAL LETTER EN' },
    { char = 'О', digraph = 'O=', name = 'CYRILLIC CAPITAL LETTER O' },
    { char = 'П', digraph = 'P=', name = 'CYRILLIC CAPITAL LETTER PE' },
    { char = 'Р', digraph = 'R=', name = 'CYRILLIC CAPITAL LETTER ER' },
    { char = 'С', digraph = 'S=', name = 'CYRILLIC CAPITAL LETTER ES' },
    { char = 'Т', digraph = 'T=', name = 'CYRILLIC CAPITAL LETTER TE' },
    { char = 'У', digraph = 'U=', name = 'CYRILLIC CAPITAL LETTER U' },
    { char = 'Ф', digraph = 'F=', name = 'CYRILLIC CAPITAL LETTER EF' },
    { char = 'Х', digraph = 'H=', name = 'CYRILLIC CAPITAL LETTER HA' },
    { char = 'Ц', digraph = 'C=', name = 'CYRILLIC CAPITAL LETTER TSE' },
    { char = 'Ч', digraph = 'C%', name = 'CYRILLIC CAPITAL LETTER CHE' },
    { char = 'Ш', digraph = 'S%', name = 'CYRILLIC CAPITAL LETTER SHA' },
    { char = 'Щ', digraph = 'Sc', name = 'CYRILLIC CAPITAL LETTER SHCHA' },
    { char = 'Ъ', digraph = '="', name = 'CYRILLIC CAPITAL LETTER HARD SIGN' },
    { char = 'Ы', digraph = 'Y=', name = 'CYRILLIC CAPITAL LETTER YERU' },
    { char = 'Ь', digraph = '%"', name = 'CYRILLIC CAPITAL LETTER SOFT SIGN' },
    { char = 'Э', digraph = 'JE', name = 'CYRILLIC CAPITAL LETTER E' },
    { char = 'Ю', digraph = 'JU', name = 'CYRILLIC CAPITAL LETTER YU' },
    { char = 'Я', digraph = 'JA', name = 'CYRILLIC CAPITAL LETTER YA' },
    { char = 'а', digraph = 'a=', name = 'CYRILLIC SMALL LETTER A' },
    { char = 'б', digraph = 'b=', name = 'CYRILLIC SMALL LETTER BE' },
    { char = 'в', digraph = 'v=', name = 'CYRILLIC SMALL LETTER VE' },
    { char = 'г', digraph = 'g=', name = 'CYRILLIC SMALL LETTER GHE' },
    { char = 'д', digraph = 'd=', name = 'CYRILLIC SMALL LETTER DE' },
    { char = 'е', digraph = 'e=', name = 'CYRILLIC SMALL LETTER IE' },
    { char = 'ж', digraph = 'z%', name = 'CYRILLIC SMALL LETTER ZHE' },
    { char = 'з', digraph = 'z=', name = 'CYRILLIC SMALL LETTER ZE' },
    { char = 'и', digraph = 'i=', name = 'CYRILLIC SMALL LETTER I' },
    { char = 'й', digraph = 'j=', name = 'CYRILLIC SMALL LETTER SHORT I' },
    { char = 'к', digraph = 'k=', name = 'CYRILLIC SMALL LETTER KA' },
    { char = 'л', digraph = 'l=', name = 'CYRILLIC SMALL LETTER EL' },
    { char = 'м', digraph = 'm=', name = 'CYRILLIC SMALL LETTER EM' },
    { char = 'н', digraph = 'n=', name = 'CYRILLIC SMALL LETTER EN' },
    { char = 'о', digraph = 'o=', name = 'CYRILLIC SMALL LETTER O' },
    { char = 'п', digraph = 'p=', name = 'CYRILLIC SMALL LETTER PE' },
    { char = 'р', digraph = 'r=', name = 'CYRILLIC SMALL LETTER ER' },
    { char = 'с', digraph = 's=', name = 'CYRILLIC SMALL LETTER ES' },
    { char = 'т', digraph = 't=', name = 'CYRILLIC SMALL LETTER TE' },
    { char = 'у', digraph = 'u=', name = 'CYRILLIC SMALL LETTER U' },
    { char = 'ф', digraph = 'f=', name = 'CYRILLIC SMALL LETTER EF' },
    { char = 'х', digraph = 'h=', name = 'CYRILLIC SMALL LETTER HA' },
    { char = 'ц', digraph = 'c=', name = 'CYRILLIC SMALL LETTER TSE' },
    { char = 'ч', digraph = 'c%', name = 'CYRILLIC SMALL LETTER CHE' },
    { char = 'ш', digraph = 's%', name = 'CYRILLIC SMALL LETTER SHA' },
    { char = 'щ', digraph = 'sc', name = 'CYRILLIC SMALL LETTER SHCHA' },
    { char = 'ъ', digraph = '=\'', name = 'CYRILLIC SMALL LETTER HARD SIGN' },
    { char = 'ы', digraph = 'y=', name = 'CYRILLIC SMALL LETTER YERU' },
    { char = 'ь', digraph = '%\'', name = 'CYRILLIC SMALL LETTER SOFT SIGN' },
    { char = 'э', digraph = 'je', name = 'CYRILLIC SMALL LETTER E' },
    { char = 'ю', digraph = 'ju', name = 'CYRILLIC SMALL LETTER YU' },
    { char = 'я', digraph = 'ja', name = 'CYRILLIC SMALL LETTER YA' },
    { char = 'ё', digraph = 'io', name = 'CYRILLIC SMALL LETTER IO' },
    { char = 'ђ', digraph = 'd%', name = 'CYRILLIC SMALL LETTER DJE' },
    { char = 'ѓ', digraph = 'g%', name = 'CYRILLIC SMALL LETTER GJE' },
    { char = 'є', digraph = 'ie', name = 'CYRILLIC SMALL LETTER UKRAINIAN IE' },
    { char = 'ѕ', digraph = 'ds', name = 'CYRILLIC SMALL LETTER DZE' },
    { char = 'і', digraph = 'ii', name = 'CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I' },
    { char = 'ї', digraph = 'yi', name = 'CYRILLIC SMALL LETTER YI' },
    { char = 'ј', digraph = 'j%', name = 'CYRILLIC SMALL LETTER JE' },
    { char = 'љ', digraph = 'lj', name = 'CYRILLIC SMALL LETTER LJE' },
    { char = 'њ', digraph = 'nj', name = 'CYRILLIC SMALL LETTER NJE' },
    { char = 'ћ', digraph = 'ts', name = 'CYRILLIC SMALL LETTER TSHE' },
    { char = 'ќ', digraph = 'kj', name = 'CYRILLIC SMALL LETTER KJE' },
    { char = 'ў', digraph = 'v%', name = 'CYRILLIC SMALL LETTER SHORT U' },
    { char = 'џ', digraph = 'dz', name = 'CYRILLIC SMALL LETTER DZHE' },
    { char = 'Ѣ', digraph = 'Y3', name = 'CYRILLIC CAPITAL LETTER YAT' },
    { char = 'ѣ', digraph = 'y3', name = 'CYRILLIC SMALL LETTER YAT' },
    { char = 'Ѫ', digraph = 'O3', name = 'CYRILLIC CAPITAL LETTER BIG YUS' },
    { char = 'ѫ', digraph = 'o3', name = 'CYRILLIC SMALL LETTER BIG YUS' },
    { char = 'Ѳ', digraph = 'F3', name = 'CYRILLIC CAPITAL LETTER FITA' },
    { char = 'ѳ', digraph = 'f3', name = 'CYRILLIC SMALL LETTER FITA' },
    { char = 'Ѵ', digraph = 'V3', name = 'CYRILLIC CAPITAL LETTER IZHITSA' },
    { char = 'ѵ', digraph = 'v3', name = 'CYRILLIC SMALL LETTER IZHITSA' },
    { char = 'Ҁ', digraph = 'C3', name = 'CYRILLIC CAPITAL LETTER KOPPA' },
    { char = 'ҁ', digraph = 'c3', name = 'CYRILLIC SMALL LETTER KOPPA' },
    { char = 'Ґ', digraph = 'G3', name = 'CYRILLIC CAPITAL LETTER GHE WITH UPTURN' },
    { char = 'ґ', digraph = 'g3', name = 'CYRILLIC SMALL LETTER GHE WITH UPTURN' },
    { char = 'א', digraph = 'A+', name = 'HEBREW LETTER ALEF' },
    { char = 'ב', digraph = 'B+', name = 'HEBREW LETTER BET' },
    { char = 'ג', digraph = 'G+', name = 'HEBREW LETTER GIMEL' },
    { char = 'ד', digraph = 'D+', name = 'HEBREW LETTER DALET' },
    { char = 'ה', digraph = 'H+', name = 'HEBREW LETTER HE' },
    { char = 'ו', digraph = 'W+', name = 'HEBREW LETTER VAV' },
    { char = 'ז', digraph = 'Z+', name = 'HEBREW LETTER ZAYIN' },
    { char = 'ח', digraph = 'X+', name = 'HEBREW LETTER HET' },
    { char = 'ט', digraph = 'Tj', name = 'HEBREW LETTER TET' },
    { char = 'י', digraph = 'J+', name = 'HEBREW LETTER YOD' },
    { char = 'ך', digraph = 'K%', name = 'HEBREW LETTER FINAL KAF' },
    { char = 'כ', digraph = 'K+', name = 'HEBREW LETTER KAF' },
    { char = 'ל', digraph = 'L+', name = 'HEBREW LETTER LAMED' },
    { char = 'ם', digraph = 'M%', name = 'HEBREW LETTER FINAL MEM' },
    { char = 'מ', digraph = 'M+', name = 'HEBREW LETTER MEM' },
    { char = 'ן', digraph = 'N%', name = 'HEBREW LETTER FINAL NUN `' },
    { char = 'נ', digraph = 'N+', name = 'HEBREW LETTER NUN `' },
    { char = 'ס', digraph = 'S+', name = 'HEBREW LETTER SAMEKH' },
    { char = 'ע', digraph = 'E+', name = 'HEBREW LETTER AYIN' },
    { char = 'ף', digraph = 'P%', name = 'HEBREW LETTER FINAL PE' },
    { char = 'פ', digraph = 'P+', name = 'HEBREW LETTER PE' },
    { char = 'ץ', digraph = 'Zj', name = 'HEBREW LETTER FINAL TSADI' },
    { char = 'צ', digraph = 'ZJ', name = 'HEBREW LETTER TSADI' },
    { char = 'ק', digraph = 'Q+', name = 'HEBREW LETTER QOF' },
    { char = 'ר', digraph = 'R+', name = 'HEBREW LETTER RESH' },
    { char = 'ש', digraph = 'Sh', name = 'HEBREW LETTER SHIN' },
    { char = 'ת', digraph = 'T+', name = 'HEBREW LETTER TAV' },
    { char = '،', digraph = ',+', name = 'ARABIC COMMA' },
    { char = '؛', digraph = ';+', name = 'ARABIC SEMICOLON' },
    { char = '؟', digraph = '?+', name = 'ARABIC QUESTION MARK' },
    { char = 'ء', digraph = 'H\'', name = 'ARABIC LETTER HAMZA' },
    { char = 'آ', digraph = 'aM', name = 'ARABIC LETTER ALEF WITH MADDA ABOVE' },
    { char = 'أ', digraph = 'aH', name = 'ARABIC LETTER ALEF WITH HAMZA ABOVE' },
    { char = 'ؤ', digraph = 'wH', name = 'ARABIC LETTER WAW WITH HAMZA ABOVE' },
    { char = 'إ', digraph = 'ah', name = 'ARABIC LETTER ALEF WITH HAMZA BELOW' },
    { char = 'ئ', digraph = 'yH', name = 'ARABIC LETTER YEH WITH HAMZA ABOVE' },
    { char = 'ا', digraph = 'a+', name = 'ARABIC LETTER ALEF' },
    { char = 'ب', digraph = 'b+', name = 'ARABIC LETTER BEH' },
    { char = 'ة', digraph = 'tm', name = 'ARABIC LETTER TEH MARBUTA' },
    { char = 'ت', digraph = 't+', name = 'ARABIC LETTER TEH' },
    { char = 'ث', digraph = 'tk', name = 'ARABIC LETTER THEH' },
    { char = 'ج', digraph = 'g+', name = 'ARABIC LETTER JEEM' },
    { char = 'ح', digraph = 'hk', name = 'ARABIC LETTER HAH' },
    { char = 'خ', digraph = 'x+', name = 'ARABIC LETTER KHAH' },
    { char = 'د', digraph = 'd+', name = 'ARABIC LETTER DAL' },
    { char = 'ذ', digraph = 'dk', name = 'ARABIC LETTER THAL' },
    { char = 'ر', digraph = 'r+', name = 'ARABIC LETTER REH' },
    { char = 'ز', digraph = 'z+', name = 'ARABIC LETTER ZAIN' },
    { char = 'س', digraph = 's+', name = 'ARABIC LETTER SEEN' },
    { char = 'ش', digraph = 'sn', name = 'ARABIC LETTER SHEEN' },
    { char = 'ص', digraph = 'c+', name = 'ARABIC LETTER SAD' },
    { char = 'ض', digraph = 'dd', name = 'ARABIC LETTER DAD' },
    { char = 'ط', digraph = 'tj', name = 'ARABIC LETTER TAH' },
    { char = 'ظ', digraph = 'zH', name = 'ARABIC LETTER ZAH' },
    { char = 'ع', digraph = 'e+', name = 'ARABIC LETTER AIN' },
    { char = 'غ', digraph = 'i+', name = 'ARABIC LETTER GHAIN' },
    { char = 'ـ', digraph = '++', name = 'ARABIC TATWEEL' },
    { char = 'ف', digraph = 'f+', name = 'ARABIC LETTER FEH' },
    { char = 'ق', digraph = 'q+', name = 'ARABIC LETTER QAF' },
    { char = 'ك', digraph = 'k+', name = 'ARABIC LETTER KAF' },
    { char = 'ل', digraph = 'l+', name = 'ARABIC LETTER LAM' },
    { char = 'م', digraph = 'm+', name = 'ARABIC LETTER MEEM' },
    { char = 'ن', digraph = 'n+', name = 'ARABIC LETTER NOON' },
    { char = 'ه', digraph = 'h+', name = 'ARABIC LETTER HEH' },
    { char = 'و', digraph = 'w+', name = 'ARABIC LETTER WAW' },
    { char = 'ى', digraph = 'j+', name = 'ARABIC LETTER ALEF MAKSURA' },
    { char = 'ي', digraph = 'y+', name = 'ARABIC LETTER YEH' },
    { char = 'ًً\'', digraph = ':+', name = 'FATHATAN' },
    { char = 'ٌ ٌ', digraph = '"+', name = 'DAMMATAN' },
    { char = 'ٍ ٍ', digraph = '=+', name = 'KASRATAN' },
    { char = 'َ َ', digraph = '/+', name = 'FATHA' },
    { char = 'ُ ', digraph = '\'+', name = 'DAMMA' },
    { char = 'ِ ', digraph = '1+', name = 'KASRA' },
    { char = 'ّ ', digraph = '3+', name = 'SHADDA' },
    { char = 'ْ ', digraph = '0+', name = 'SUKUN' },
    { char = 'ٰ ', digraph = 'aS', name = 'LETTER SUPERSCRIPT ALEF' },
    { char = 'پ', digraph = 'p+', name = 'ARABIC LETTER PEH' },
    { char = 'ڤ', digraph = 'v+', name = 'ARABIC LETTER VEH' },
    { char = 'گ', digraph = 'gf', name = 'ARABIC LETTER GAF' },
    { char = '۰', digraph = '0a', name = 'EXTENDED ARABIC-INDIC DIGIT ZERO' },
    { char = '۱', digraph = '1a', name = 'EXTENDED ARABIC-INDIC DIGIT ONE' },
    { char = '۲', digraph = '2a', name = 'EXTENDED ARABIC-INDIC DIGIT TWO' },
    { char = '۳', digraph = '3a', name = 'EXTENDED ARABIC-INDIC DIGIT THREE' },
    { char = '۴', digraph = '4a', name = 'EXTENDED ARABIC-INDIC DIGIT FOUR' },
    { char = '۵', digraph = '5a', name = 'EXTENDED ARABIC-INDIC DIGIT FIVE' },
    { char = '۶', digraph = '6a', name = 'EXTENDED ARABIC-INDIC DIGIT SIX' },
    { char = '۷', digraph = '7a', name = 'EXTENDED ARABIC-INDIC DIGIT SEVEN' },
    { char = '۸', digraph = '8a', name = 'EXTENDED ARABIC-INDIC DIGIT EIGHT' },
    { char = '۹', digraph = '9a', name = 'EXTENDED ARABIC-INDIC DIGIT NINE' },
    { char = 'Ḃ', digraph = 'B.', name = 'LATIN CAPITAL LETTER B WITH DOT ABOVE' },
    { char = 'ḃ', digraph = 'b.', name = 'LATIN SMALL LETTER B WITH DOT ABOVE' },
    { char = 'Ḇ', digraph = 'B_', name = 'LATIN CAPITAL LETTER B WITH LINE BELOW' },
    { char = 'ḇ', digraph = 'b_', name = 'LATIN SMALL LETTER B WITH LINE BELOW' },
    { char = 'Ḋ', digraph = 'D.', name = 'LATIN CAPITAL LETTER D WITH DOT ABOVE' },
    { char = 'ḋ', digraph = 'd.', name = 'LATIN SMALL LETTER D WITH DOT ABOVE' },
    { char = 'Ḏ', digraph = 'D_', name = 'LATIN CAPITAL LETTER D WITH LINE BELOW' },
    { char = 'ḏ', digraph = 'd_', name = 'LATIN SMALL LETTER D WITH LINE BELOW' },
    { char = 'Ḑ', digraph = 'D,', name = 'LATIN CAPITAL LETTER D WITH CEDILLA' },
    { char = 'ḑ', digraph = 'd,', name = 'LATIN SMALL LETTER D WITH CEDILLA' },
    { char = 'Ḟ', digraph = 'F.', name = 'LATIN CAPITAL LETTER F WITH DOT ABOVE' },
    { char = 'ḟ', digraph = 'f.', name = 'LATIN SMALL LETTER F WITH DOT ABOVE' },
    { char = 'Ḡ', digraph = 'G-', name = 'LATIN CAPITAL LETTER G WITH MACRON' },
    { char = 'ḡ', digraph = 'g-', name = 'LATIN SMALL LETTER G WITH MACRON' },
    { char = 'Ḣ', digraph = 'H.', name = 'LATIN CAPITAL LETTER H WITH DOT ABOVE' },
    { char = 'ḣ', digraph = 'h.', name = 'LATIN SMALL LETTER H WITH DOT ABOVE' },
    { char = 'Ḧ', digraph = 'H:', name = 'LATIN CAPITAL LETTER H WITH DIAERESIS' },
    { char = 'ḧ', digraph = 'h:', name = 'LATIN SMALL LETTER H WITH DIAERESIS' },
    { char = 'Ḩ', digraph = 'H,', name = 'LATIN CAPITAL LETTER H WITH CEDILLA' },
    { char = 'ḩ', digraph = 'h,', name = 'LATIN SMALL LETTER H WITH CEDILLA' },
    { char = 'Ḱ', digraph = 'K\'', name = 'LATIN CAPITAL LETTER K WITH ACUTE' },
    { char = 'ḱ', digraph = 'k\'', name = 'LATIN SMALL LETTER K WITH ACUTE' },
    { char = 'Ḵ', digraph = 'K_', name = 'LATIN CAPITAL LETTER K WITH LINE BELOW' },
    { char = 'ḵ', digraph = 'k_', name = 'LATIN SMALL LETTER K WITH LINE BELOW' },
    { char = 'Ḻ', digraph = 'L_', name = 'LATIN CAPITAL LETTER L WITH LINE BELOW' },
    { char = 'ḻ', digraph = 'l_', name = 'LATIN SMALL LETTER L WITH LINE BELOW' },
    { char = 'Ḿ', digraph = 'M\'', name = 'LATIN CAPITAL LETTER M WITH ACUTE' },
    { char = 'ḿ', digraph = 'm\'', name = 'LATIN SMALL LETTER M WITH ACUTE' },
    { char = 'Ṁ', digraph = 'M.', name = 'LATIN CAPITAL LETTER M WITH DOT ABOVE' },
    { char = 'ṁ', digraph = 'm.', name = 'LATIN SMALL LETTER M WITH DOT ABOVE' },
    { char = 'Ṅ', digraph = 'N.', name = 'LATIN CAPITAL LETTER N WITH DOT ABOVE `' },
    { char = 'ṅ', digraph = 'n.', name = 'LATIN SMALL LETTER N WITH DOT ABOVE `' },
    { char = 'Ṉ', digraph = 'N_', name = 'LATIN CAPITAL LETTER N WITH LINE BELOW `' },
    { char = 'ṉ', digraph = 'n_', name = 'LATIN SMALL LETTER N WITH LINE BELOW `' },
    { char = 'Ṕ', digraph = 'P\'', name = 'LATIN CAPITAL LETTER P WITH ACUTE' },
    { char = 'ṕ', digraph = 'p\'', name = 'LATIN SMALL LETTER P WITH ACUTE' },
    { char = 'Ṗ', digraph = 'P.', name = 'LATIN CAPITAL LETTER P WITH DOT ABOVE' },
    { char = 'ṗ', digraph = 'p.', name = 'LATIN SMALL LETTER P WITH DOT ABOVE' },
    { char = 'Ṙ', digraph = 'R.', name = 'LATIN CAPITAL LETTER R WITH DOT ABOVE' },
    { char = 'ṙ', digraph = 'r.', name = 'LATIN SMALL LETTER R WITH DOT ABOVE' },
    { char = 'Ṟ', digraph = 'R_', name = 'LATIN CAPITAL LETTER R WITH LINE BELOW' },
    { char = 'ṟ', digraph = 'r_', name = 'LATIN SMALL LETTER R WITH LINE BELOW' },
    { char = 'Ṡ', digraph = 'S.', name = 'LATIN CAPITAL LETTER S WITH DOT ABOVE' },
    { char = 'ṡ', digraph = 's.', name = 'LATIN SMALL LETTER S WITH DOT ABOVE' },
    { char = 'Ṫ', digraph = 'T.', name = 'LATIN CAPITAL LETTER T WITH DOT ABOVE' },
    { char = 'ṫ', digraph = 't.', name = 'LATIN SMALL LETTER T WITH DOT ABOVE' },
    { char = 'Ṯ', digraph = 'T_', name = 'LATIN CAPITAL LETTER T WITH LINE BELOW' },
    { char = 'ṯ', digraph = 't_', name = 'LATIN SMALL LETTER T WITH LINE BELOW' },
    { char = 'Ṽ', digraph = 'V?', name = 'LATIN CAPITAL LETTER V WITH TILDE' },
    { char = 'ṽ', digraph = 'v?', name = 'LATIN SMALL LETTER V WITH TILDE' },
    { char = 'Ẁ', digraph = 'W!', name = 'LATIN CAPITAL LETTER W WITH GRAVE' },
    { char = 'ẁ', digraph = 'w!', name = 'LATIN SMALL LETTER W WITH GRAVE' },
    { char = 'Ẃ', digraph = 'W\'', name = 'LATIN CAPITAL LETTER W WITH ACUTE' },
    { char = 'ẃ', digraph = 'w\'', name = 'LATIN SMALL LETTER W WITH ACUTE' },
    { char = 'Ẅ', digraph = 'W:', name = 'LATIN CAPITAL LETTER W WITH DIAERESIS' },
    { char = 'ẅ', digraph = 'w:', name = 'LATIN SMALL LETTER W WITH DIAERESIS' },
    { char = 'Ẇ', digraph = 'W.', name = 'LATIN CAPITAL LETTER W WITH DOT ABOVE' },
    { char = 'ẇ', digraph = 'w.', name = 'LATIN SMALL LETTER W WITH DOT ABOVE' },
    { char = 'Ẋ', digraph = 'X.', name = 'LATIN CAPITAL LETTER X WITH DOT ABOVE' },
    { char = 'ẋ', digraph = 'x.', name = 'LATIN SMALL LETTER X WITH DOT ABOVE' },
    { char = 'Ẍ', digraph = 'X:', name = 'LATIN CAPITAL LETTER X WITH DIAERESIS' },
    { char = 'ẍ', digraph = 'x:', name = 'LATIN SMALL LETTER X WITH DIAERESIS' },
    { char = 'Ẏ', digraph = 'Y.', name = 'LATIN CAPITAL LETTER Y WITH DOT ABOVE' },
    { char = 'ẏ', digraph = 'y.', name = 'LATIN SMALL LETTER Y WITH DOT ABOVE' },
    { char = 'Ẑ', digraph = 'Z>', name = 'LATIN CAPITAL LETTER Z WITH CIRCUMFLEX' },
    { char = 'ẑ', digraph = 'z>', name = 'LATIN SMALL LETTER Z WITH CIRCUMFLEX' },
    { char = 'Ẕ', digraph = 'Z_', name = 'LATIN CAPITAL LETTER Z WITH LINE BELOW' },
    { char = 'ẕ', digraph = 'z_', name = 'LATIN SMALL LETTER Z WITH LINE BELOW' },
    { char = 'ẖ', digraph = 'h_', name = 'LATIN SMALL LETTER H WITH LINE BELOW' },
    { char = 'ẗ', digraph = 't:', name = 'LATIN SMALL LETTER T WITH DIAERESIS' },
    { char = 'ẘ', digraph = 'w0', name = 'LATIN SMALL LETTER W WITH RING ABOVE' },
    { char = 'ẙ', digraph = 'y0', name = 'LATIN SMALL LETTER Y WITH RING ABOVE' },
    { char = 'Ả', digraph = 'A2', name = 'LATIN CAPITAL LETTER A WITH HOOK ABOVE' },
    { char = 'ả', digraph = 'a2', name = 'LATIN SMALL LETTER A WITH HOOK ABOVE' },
    { char = 'Ẻ', digraph = 'E2', name = 'LATIN CAPITAL LETTER E WITH HOOK ABOVE' },
    { char = 'ẻ', digraph = 'e2', name = 'LATIN SMALL LETTER E WITH HOOK ABOVE' },
    { char = 'Ẽ', digraph = 'E?', name = 'LATIN CAPITAL LETTER E WITH TILDE' },
    { char = 'ẽ', digraph = 'e?', name = 'LATIN SMALL LETTER E WITH TILDE' },
    { char = 'Ỉ', digraph = 'I2', name = 'LATIN CAPITAL LETTER I WITH HOOK ABOVE' },
    { char = 'ỉ', digraph = 'i2', name = 'LATIN SMALL LETTER I WITH HOOK ABOVE' },
    { char = 'Ỏ', digraph = 'O2', name = 'LATIN CAPITAL LETTER O WITH HOOK ABOVE' },
    { char = 'ỏ', digraph = 'o2', name = 'LATIN SMALL LETTER O WITH HOOK ABOVE' },
    { char = 'Ủ', digraph = 'U2', name = 'LATIN CAPITAL LETTER U WITH HOOK ABOVE' },
    { char = 'ủ', digraph = 'u2', name = 'LATIN SMALL LETTER U WITH HOOK ABOVE' },
    { char = 'Ỳ', digraph = 'Y!', name = 'LATIN CAPITAL LETTER Y WITH GRAVE' },
    { char = 'ỳ', digraph = 'y!', name = 'LATIN SMALL LETTER Y WITH GRAVE' },
    { char = 'Ỷ', digraph = 'Y2', name = 'LATIN CAPITAL LETTER Y WITH HOOK ABOVE' },
    { char = 'ỷ', digraph = 'y2', name = 'LATIN SMALL LETTER Y WITH HOOK ABOVE' },
    { char = 'Ỹ', digraph = 'Y?', name = 'LATIN CAPITAL LETTER Y WITH TILDE' },
    { char = 'ỹ', digraph = 'y?', name = 'LATIN SMALL LETTER Y WITH TILDE' },
    { char = 'ἀ', digraph = ';\'', name = 'GREEK SMALL LETTER ALPHA WITH PSILI' },
    { char = 'ἁ', digraph = ',\'', name = 'GREEK SMALL LETTER ALPHA WITH DASIA' },
    { char = 'ἂ', digraph = ';!', name = 'GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA' },
    { char = 'ἃ', digraph = ',!', name = 'GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA' },
    { char = 'ἄ', digraph = '?;', name = 'GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA' },
    { char = 'ἅ', digraph = '?,', name = 'GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA' },
    { char = 'ἆ', digraph = '!:', name = 'GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI' },
    { char = 'ἇ', digraph = '?:', name = 'GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI' },
    { char = '1', digraph = '	2', name = 'SPACE' },
    { char = '1', digraph = '	2', name = 'SPACE' },
    { char = '3', digraph = '	2', name = '-PER-EM SPACE' },
    { char = '4', digraph = '	2', name = '-PER-EM SPACE' },
    { char = '6', digraph = '	2', name = '-PER-EM SPACE' },
    { char = '1', digraph = '	2', name = 'SPACE' },
    { char = '1', digraph = '	2', name = 'SPACE' },
    { char = '‐', digraph = '-1', name = 'HYPHEN' },
    { char = '–', digraph = '-N', name = 'EN DASH `' },
    { char = '—', digraph = '-M', name = 'EM DASH' },
    { char = '―', digraph = '-3', name = 'HORIZONTAL BAR' },
    { char = '‖', digraph = '!2', name = 'DOUBLE VERTICAL LINE' },
    { char = '‗', digraph = '=2', name = 'DOUBLE LOW LINE' },
    { char = '‘', digraph = '\'6', name = 'LEFT SINGLE QUOTATION MARK' },
    { char = '’', digraph = '\'9', name = 'RIGHT SINGLE QUOTATION MARK' },
    { char = '‚', digraph = '.9', name = 'SINGLE LOW-9 QUOTATION MARK' },
    { char = '‛', digraph = '9\'', name = 'SINGLE HIGH-REVERSED-9 QUOTATION MARK' },
    { char = '“', digraph = '"6', name = 'LEFT DOUBLE QUOTATION MARK' },
    { char = '”', digraph = '"9', name = 'RIGHT DOUBLE QUOTATION MARK' },
    { char = '„', digraph = ':9', name = 'DOUBLE LOW-9 QUOTATION MARK' },
    { char = '‟', digraph = '9"', name = 'DOUBLE HIGH-REVERSED-9 QUOTATION MARK' },
    { char = '†', digraph = '/-', name = 'DAGGER' },
    { char = '‡', digraph = '/=', name = 'DOUBLE DAGGER' },
    { char = '•', digraph = 'oo', name = 'BULLET' },
    { char = '‥', digraph = '..', name = 'TWO DOT LEADER' },
    { char = '…', digraph = ',.', name = 'HORIZONTAL ELLIPSIS' },
    { char = '‰', digraph = '%0', name = 'PER MILLE SIGN' },
    { char = '′', digraph = '1\'', name = 'PRIME' },
    { char = '″', digraph = '2\'', name = 'DOUBLE PRIME' },
    { char = '‴', digraph = '3\'', name = 'TRIPLE PRIME' },
    { char = '⁗', digraph = '4\'', name = 'QUADRUPLE PRIME' },
    { char = '‵', digraph = '1"', name = 'REVERSED PRIME' },
    { char = '‶', digraph = '2"', name = 'REVERSED DOUBLE PRIME' },
    { char = '‷', digraph = '3"', name = 'REVERSED TRIPLE PRIME' },
    { char = '‸', digraph = 'Ca', name = 'CARET' },
    { char = '‹', digraph = '<1', name = 'SINGLE LEFT-POINTING ANGLE QUOTATION MARK' },
    { char = '›', digraph = '>1', name = 'SINGLE RIGHT-POINTING ANGLE QUOTATION MARK' },
    { char = '※', digraph = ':X', name = 'REFERENCE MARK' },
    { char = '‾', digraph = '\'-', name = 'OVERLINE' },
    { char = '⁄', digraph = '/f', name = 'FRACTION SLASH' },
    { char = '⁰', digraph = '0S', name = 'SUPERSCRIPT ZERO' },
    { char = '⁴', digraph = '4S', name = 'SUPERSCRIPT FOUR' },
    { char = '⁵', digraph = '5S', name = 'SUPERSCRIPT FIVE' },
    { char = '⁶', digraph = '6S', name = 'SUPERSCRIPT SIX' },
    { char = '⁷', digraph = '7S', name = 'SUPERSCRIPT SEVEN' },
    { char = '⁸', digraph = '8S', name = 'SUPERSCRIPT EIGHT' },
    { char = '⁹', digraph = '9S', name = 'SUPERSCRIPT NINE' },
    { char = '⁺', digraph = '+S', name = 'SUPERSCRIPT PLUS SIGN' },
    { char = '⁻', digraph = '-S', name = 'SUPERSCRIPT MINUS' },
    { char = '⁼', digraph = '=S', name = 'SUPERSCRIPT EQUALS SIGN' },
    { char = '⁽', digraph = '(S', name = 'SUPERSCRIPT LEFT PARENTHESIS' },
    { char = '⁾', digraph = ')S', name = 'SUPERSCRIPT RIGHT PARENTHESIS' },
    { char = 'ⁿ', digraph = 'nS', name = 'SUPERSCRIPT LATIN SMALL LETTER N `' },
    { char = '₀', digraph = '0s', name = 'SUBSCRIPT ZERO' },
    { char = '₁', digraph = '1s', name = 'SUBSCRIPT ONE' },
    { char = '₂', digraph = '2s', name = 'SUBSCRIPT TWO' },
    { char = '₃', digraph = '3s', name = 'SUBSCRIPT THREE' },
    { char = '₄', digraph = '4s', name = 'SUBSCRIPT FOUR' },
    { char = '₅', digraph = '5s', name = 'SUBSCRIPT FIVE' },
    { char = '₆', digraph = '6s', name = 'SUBSCRIPT SIX' },
    { char = '₇', digraph = '7s', name = 'SUBSCRIPT SEVEN' },
    { char = '₈', digraph = '8s', name = 'SUBSCRIPT EIGHT' },
    { char = '₉', digraph = '9s', name = 'SUBSCRIPT NINE' },
    { char = '₊', digraph = '+s', name = 'SUBSCRIPT PLUS SIGN' },
    { char = '₋', digraph = '-s', name = 'SUBSCRIPT MINUS' },
    { char = '₌', digraph = '=s', name = 'SUBSCRIPT EQUALS SIGN' },
    { char = '₍', digraph = '(s', name = 'SUBSCRIPT LEFT PARENTHESIS' },
    { char = '₎', digraph = ')s', name = 'SUBSCRIPT RIGHT PARENTHESIS' },
    { char = '₤', digraph = 'Li', name = 'LIRA SIGN' },
    { char = '₧', digraph = 'Pt', name = 'PESETA SIGN' },
    { char = '₩', digraph = 'W=', name = 'WON SIGN' },
    { char = '€', digraph = 'Eu', name = 'EURO SIGN' },
    { char = '₽', digraph = '=R', name = 'ROUBLE SIGN' },
    { char = '₽', digraph = '=P', name = 'ROUBLE SIGN' },
    { char = '℃', digraph = 'oC', name = 'DEGREE CELSIUS' },
    { char = '℅', digraph = 'co', name = 'CARE OF' },
    { char = '℉', digraph = 'oF', name = 'DEGREE FAHRENHEIT' },
    { char = '№', digraph = 'N0', name = 'NUMERO SIGN' },
    { char = '℗', digraph = 'PO', name = 'SOUND RECORDING COPYRIGHT' },
    { char = '℞', digraph = 'Rx', name = 'PRESCRIPTION TAKE' },
    { char = '℠', digraph = 'SM', name = 'SERVICE MARK' },
    { char = '™', digraph = 'TM', name = 'TRADE MARK SIGN' },
    { char = 'Ω', digraph = 'Om', name = 'OHM SIGN' },
    { char = 'Å', digraph = 'AO', name = 'ANGSTROM SIGN' },
    { char = '⅓', digraph = '13', name = 'VULGAR FRACTION ONE THIRD' },
    { char = '⅔', digraph = '23', name = 'VULGAR FRACTION TWO THIRDS' },
    { char = '⅕', digraph = '15', name = 'VULGAR FRACTION ONE FIFTH' },
    { char = '⅖', digraph = '25', name = 'VULGAR FRACTION TWO FIFTHS' },
    { char = '⅗', digraph = '35', name = 'VULGAR FRACTION THREE FIFTHS' },
    { char = '⅘', digraph = '45', name = 'VULGAR FRACTION FOUR FIFTHS' },
    { char = '⅙', digraph = '16', name = 'VULGAR FRACTION ONE SIXTH' },
    { char = '⅚', digraph = '56', name = 'VULGAR FRACTION FIVE SIXTHS' },
    { char = '⅛', digraph = '18', name = 'VULGAR FRACTION ONE EIGHTH' },
    { char = '⅜', digraph = '38', name = 'VULGAR FRACTION THREE EIGHTHS' },
    { char = '⅝', digraph = '58', name = 'VULGAR FRACTION FIVE EIGHTHS' },
    { char = '⅞', digraph = '78', name = 'VULGAR FRACTION SEVEN EIGHTHS' },
    { char = 'Ⅰ', digraph = '1R', name = 'ROMAN NUMERAL ONE' },
    { char = 'Ⅱ', digraph = '2R', name = 'ROMAN NUMERAL TWO' },
    { char = 'Ⅲ', digraph = '3R', name = 'ROMAN NUMERAL THREE' },
    { char = 'Ⅳ', digraph = '4R', name = 'ROMAN NUMERAL FOUR' },
    { char = 'Ⅴ', digraph = '5R', name = 'ROMAN NUMERAL FIVE' },
    { char = 'Ⅵ', digraph = '6R', name = 'ROMAN NUMERAL SIX' },
    { char = 'Ⅶ', digraph = '7R', name = 'ROMAN NUMERAL SEVEN' },
    { char = 'Ⅷ', digraph = '8R', name = 'ROMAN NUMERAL EIGHT' },
    { char = 'Ⅸ', digraph = '9R', name = 'ROMAN NUMERAL NINE' },
    { char = 'Ⅹ', digraph = 'aR', name = 'ROMAN NUMERAL TEN' },
    { char = 'Ⅺ', digraph = 'bR', name = 'ROMAN NUMERAL ELEVEN' },
    { char = 'Ⅻ', digraph = 'cR', name = 'ROMAN NUMERAL TWELVE' },
    { char = 'ⅰ', digraph = '1r', name = 'SMALL ROMAN NUMERAL ONE' },
    { char = 'ⅱ', digraph = '2r', name = 'SMALL ROMAN NUMERAL TWO' },
    { char = 'ⅲ', digraph = '3r', name = 'SMALL ROMAN NUMERAL THREE' },
    { char = 'ⅳ', digraph = '4r', name = 'SMALL ROMAN NUMERAL FOUR' },
    { char = 'ⅴ', digraph = '5r', name = 'SMALL ROMAN NUMERAL FIVE' },
    { char = 'ⅵ', digraph = '6r', name = 'SMALL ROMAN NUMERAL SIX' },
    { char = 'ⅶ', digraph = '7r', name = 'SMALL ROMAN NUMERAL SEVEN' },
    { char = 'ⅷ', digraph = '8r', name = 'SMALL ROMAN NUMERAL EIGHT' },
    { char = 'ⅸ', digraph = '9r', name = 'SMALL ROMAN NUMERAL NINE' },
    { char = 'ⅹ', digraph = 'ar', name = 'SMALL ROMAN NUMERAL TEN' },
    { char = 'ⅺ', digraph = 'br', name = 'SMALL ROMAN NUMERAL ELEVEN' },
    { char = 'ⅻ', digraph = 'cr', name = 'SMALL ROMAN NUMERAL TWELVE' },
    { char = '←', digraph = '<-', name = 'LEFTWARDS ARROW' },
    { char = '↑', digraph = '-!', name = 'UPWARDS ARROW' },
    { char = '→', digraph = '->', name = 'RIGHTWARDS ARROW' },
    { char = '↓', digraph = '-v', name = 'DOWNWARDS ARROW' },
    { char = '↔', digraph = '<>', name = 'LEFT RIGHT ARROW' },
    { char = '↕', digraph = 'UD', name = 'UP DOWN ARROW' },
    { char = '⇐', digraph = '<=', name = 'LEFTWARDS DOUBLE ARROW' },
    { char = '⇒', digraph = '=>', name = 'RIGHTWARDS DOUBLE ARROW' },
    { char = '⇔', digraph = '==', name = 'LEFT RIGHT DOUBLE ARROW' },
    { char = '∀', digraph = 'FA', name = 'FOR ALL' },
    { char = '∂', digraph = 'dP', name = 'PARTIAL DIFFERENTIAL' },
    { char = '∃', digraph = 'TE', name = 'THERE EXISTS' },
    { char = '∅', digraph = '/0', name = 'EMPTY SET' },
    { char = '∆', digraph = 'DE', name = 'INCREMENT' },
    { char = '∇', digraph = 'NB', name = 'NABLA' },
    { char = '∈', digraph = '(-', name = 'ELEMENT OF' },
    { char = '∋', digraph = '-)', name = 'CONTAINS AS MEMBER' },
    { char = '∏', digraph = '*P', name = 'N-ARY PRODUCT `' },
    { char = '∑', digraph = '+Z', name = 'N-ARY SUMMATION `' },
    { char = '−', digraph = '-2', name = 'MINUS SIGN' },
    { char = '∓', digraph = '-+', name = 'MINUS-OR-PLUS SIGN' },
    { char = '∗', digraph = '*-', name = 'ASTERISK OPERATOR' },
    { char = '∘', digraph = 'Ob', name = 'RING OPERATOR' },
    { char = '∙', digraph = 'Sb', name = 'BULLET OPERATOR' },
    { char = '√', digraph = 'RT', name = 'SQUARE ROOT' },
    { char = '∝', digraph = '0(', name = 'PROPORTIONAL TO' },
    { char = '∞', digraph = '00', name = 'INFINITY' },
    { char = '∟', digraph = '-L', name = 'RIGHT ANGLE' },
    { char = '∠', digraph = '-V', name = 'ANGLE' },
    { char = '∥', digraph = 'PP', name = 'PARALLEL TO' },
    { char = '∧', digraph = 'AN', name = 'LOGICAL AND' },
    { char = '∨', digraph = 'OR', name = 'LOGICAL OR' },
    { char = '∩', digraph = '(U', name = 'INTERSECTION' },
    { char = '∪', digraph = ')U', name = 'UNION' },
    { char = '∫', digraph = 'In', name = 'INTEGRAL' },
    { char = '∬', digraph = 'DI', name = 'DOUBLE INTEGRAL' },
    { char = '∮', digraph = 'Io', name = 'CONTOUR INTEGRAL' },
    { char = '∴', digraph = '.:', name = 'THEREFORE' },
    { char = '∵', digraph = ':.', name = 'BECAUSE' },
    { char = '∶', digraph = ':R', name = 'RATIO' },
    { char = '∷', digraph = '::', name = 'PROPORTION' },
    { char = '∼', digraph = '?1', name = 'TILDE OPERATOR' },
    { char = '∾', digraph = 'CG', name = 'INVERTED LAZY S' },
    { char = '≃', digraph = '?-', name = 'ASYMPTOTICALLY EQUAL TO' },
    { char = '≅', digraph = '?=', name = 'APPROXIMATELY EQUAL TO' },
    { char = '≈', digraph = '?2', name = 'ALMOST EQUAL TO' },
    { char = '≌', digraph = '=?', name = 'ALL EQUAL TO' },
    { char = '≓', digraph = 'HI', name = 'IMAGE OF OR APPROXIMATELY EQUAL TO' },
    { char = '≠', digraph = '!=', name = 'NOT EQUAL TO' },
    { char = '≡', digraph = '=3', name = 'IDENTICAL TO' },
    { char = '≤', digraph = '=<', name = 'LESS-THAN OR EQUAL TO' },
    { char = '≥', digraph = '>=', name = 'GREATER-THAN OR EQUAL TO' },
    { char = '≪', digraph = '<*', name = 'MUCH LESS-THAN' },
    { char = '≫', digraph = '*>', name = 'MUCH GREATER-THAN' },
    { char = '≮', digraph = '!<', name = 'NOT LESS-THAN' },
    { char = '≯', digraph = '!>', name = 'NOT GREATER-THAN' },
    { char = '⊂', digraph = '(C', name = 'SUBSET OF' },
    { char = '⊃', digraph = ')C', name = 'SUPERSET OF' },
    { char = '⊆', digraph = '(_', name = 'SUBSET OF OR EQUAL TO' },
    { char = '⊇', digraph = ')_', name = 'SUPERSET OF OR EQUAL TO' },
    { char = '⊙', digraph = '0.', name = 'CIRCLED DOT OPERATOR' },
    { char = '⊚', digraph = '02', name = 'CIRCLED RING OPERATOR' },
    { char = '⊥', digraph = '-T', name = 'UP TACK' },
    { char = '⋅', digraph = '.P', name = 'DOT OPERATOR' },
    { char = '⋮', digraph = ':3', name = 'VERTICAL ELLIPSIS' },
    { char = '⋯', digraph = '.3', name = 'MIDLINE HORIZONTAL ELLIPSIS' },
    { char = '⌂', digraph = 'Eh', name = 'HOUSE' },
    { char = '⌈', digraph = '<7', name = 'LEFT CEILING' },
    { char = '⌉', digraph = '>7', name = 'RIGHT CEILING' },
    { char = '⌊', digraph = '7<', name = 'LEFT FLOOR' },
    { char = '⌋', digraph = '7>', name = 'RIGHT FLOOR' },
    { char = '⌐', digraph = 'NI', name = 'REVERSED NOT SIGN' },
    { char = '⌒', digraph = '(A', name = 'ARC' },
    { char = '⌕', digraph = 'TR', name = 'TELEPHONE RECORDER' },
    { char = '⌠', digraph = 'Iu', name = 'TOP HALF INTEGRAL' },
    { char = '⌡', digraph = 'Il', name = 'BOTTOM HALF INTEGRAL' },
    { char = '〈', digraph = '</', name = 'LEFT-POINTING ANGLE BRACKET' },
    { char = '〉', digraph = '/>', name = 'RIGHT-POINTING ANGLE BRACKET' },
    { char = '␣', digraph = 'Vs', name = 'OPEN BOX' },
    { char = '⑀', digraph = '1h', name = 'OCR HOOK' },
    { char = '⑁', digraph = '3h', name = 'OCR CHAIR' },
    { char = '⑂', digraph = '2h', name = 'OCR FORK' },
    { char = '⑃', digraph = '4h', name = 'OCR INVERTED FORK' },
    { char = '⑆', digraph = '1j', name = 'OCR BRANCH BANK IDENTIFICATION' },
    { char = '⑇', digraph = '2j', name = 'OCR AMOUNT OF CHECK' },
    { char = '⑈', digraph = '3j', name = 'OCR DASH' },
    { char = '⑉', digraph = '4j', name = 'OCR CUSTOMER ACCOUNT NUMBER' },
    { char = '⒈', digraph = '1.', name = 'DIGIT ONE FULL STOP' },
    { char = '⒉', digraph = '2.', name = 'DIGIT TWO FULL STOP' },
    { char = '⒊', digraph = '3.', name = 'DIGIT THREE FULL STOP' },
    { char = '⒋', digraph = '4.', name = 'DIGIT FOUR FULL STOP' },
    { char = '⒌', digraph = '5.', name = 'DIGIT FIVE FULL STOP' },
    { char = '⒍', digraph = '6.', name = 'DIGIT SIX FULL STOP' },
    { char = '⒎', digraph = '7.', name = 'DIGIT SEVEN FULL STOP' },
    { char = '⒏', digraph = '8.', name = 'DIGIT EIGHT FULL STOP' },
    { char = '⒐', digraph = '9.', name = 'DIGIT NINE FULL STOP' },
    { char = '─', digraph = 'hh', name = 'BOX DRAWINGS LIGHT HORIZONTAL' },
    { char = '━', digraph = 'HH', name = 'BOX DRAWINGS HEAVY HORIZONTAL' },
    { char = '│', digraph = 'vv', name = 'BOX DRAWINGS LIGHT VERTICAL' },
    { char = '┃', digraph = 'VV', name = 'BOX DRAWINGS HEAVY VERTICAL' },
    { char = '┄', digraph = '3-', name = 'BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL' },
    { char = '┅', digraph = '3_', name = 'BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL' },
    { char = '┆', digraph = '3!', name = 'BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL' },
    { char = '┇', digraph = '3/', name = 'BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL' },
    { char = '┈', digraph = '4-', name = 'BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL' },
    { char = '┉', digraph = '4_', name = 'BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL' },
    { char = '┊', digraph = '4!', name = 'BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL' },
    { char = '┋', digraph = '4/', name = 'BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL' },
    { char = '┌', digraph = 'dr', name = 'BOX DRAWINGS LIGHT DOWN AND RIGHT' },
    { char = '┍', digraph = 'dR', name = 'BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY' },
    { char = '┎', digraph = 'Dr', name = 'BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT' },
    { char = '┏', digraph = 'DR', name = 'BOX DRAWINGS HEAVY DOWN AND RIGHT' },
    { char = '┐', digraph = 'dl', name = 'BOX DRAWINGS LIGHT DOWN AND LEFT' },
    { char = '┑', digraph = 'dL', name = 'BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY' },
    { char = '┒', digraph = 'Dl', name = 'BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT' },
    { char = '┓', digraph = 'LD', name = 'BOX DRAWINGS HEAVY DOWN AND LEFT' },
    { char = '└', digraph = 'ur', name = 'BOX DRAWINGS LIGHT UP AND RIGHT' },
    { char = '┕', digraph = 'uR', name = 'BOX DRAWINGS UP LIGHT AND RIGHT HEAVY' },
    { char = '┖', digraph = 'Ur', name = 'BOX DRAWINGS UP HEAVY AND RIGHT LIGHT' },
    { char = '┗', digraph = 'UR', name = 'BOX DRAWINGS HEAVY UP AND RIGHT' },
    { char = '┘', digraph = 'ul', name = 'BOX DRAWINGS LIGHT UP AND LEFT' },
    { char = '┙', digraph = 'uL', name = 'BOX DRAWINGS UP LIGHT AND LEFT HEAVY' },
    { char = '┚', digraph = 'Ul', name = 'BOX DRAWINGS UP HEAVY AND LEFT LIGHT' },
    { char = '┛', digraph = 'UL', name = 'BOX DRAWINGS HEAVY UP AND LEFT' },
    { char = '├', digraph = 'vr', name = 'BOX DRAWINGS LIGHT VERTICAL AND RIGHT' },
    { char = '┝', digraph = 'vR', name = 'BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY' },
    { char = '┠', digraph = 'Vr', name = 'BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT' },
    { char = '┣', digraph = 'VR', name = 'BOX DRAWINGS HEAVY VERTICAL AND RIGHT' },
    { char = '┤', digraph = 'vl', name = 'BOX DRAWINGS LIGHT VERTICAL AND LEFT' },
    { char = '┥', digraph = 'vL', name = 'BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY' },
    { char = '┨', digraph = 'Vl', name = 'BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT' },
    { char = '┫', digraph = 'VL', name = 'BOX DRAWINGS HEAVY VERTICAL AND LEFT' },
    { char = '┬', digraph = 'dh', name = 'BOX DRAWINGS LIGHT DOWN AND HORIZONTAL' },
    { char = '┯', digraph = 'dH', name = 'BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY' },
    { char = '┰', digraph = 'Dh', name = 'BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT' },
    { char = '┳', digraph = 'DH', name = 'BOX DRAWINGS HEAVY DOWN AND HORIZONTAL' },
    { char = '┴', digraph = 'uh', name = 'BOX DRAWINGS LIGHT UP AND HORIZONTAL' },
    { char = '┷', digraph = 'uH', name = 'BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY' },
    { char = '┸', digraph = 'Uh', name = 'BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT' },
    { char = '┻', digraph = 'UH', name = 'BOX DRAWINGS HEAVY UP AND HORIZONTAL' },
    { char = '┼', digraph = 'vh', name = 'BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL' },
    { char = '┿', digraph = 'vH', name = 'BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY' },
    { char = '╂', digraph = 'Vh', name = 'BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT' },
    { char = '╋', digraph = 'VH', name = 'BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL' },
    { char = '╱', digraph = 'FD', name = 'BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT' },
    { char = '╲', digraph = 'BD', name = 'BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT' },
    { char = '▀', digraph = 'TB', name = 'UPPER HALF BLOCK' },
    { char = '▄', digraph = 'LB', name = 'LOWER HALF BLOCK' },
    { char = '█', digraph = 'FB', name = 'FULL BLOCK' },
    { char = '▌', digraph = 'lB', name = 'LEFT HALF BLOCK' },
    { char = '▐', digraph = 'RB', name = 'RIGHT HALF BLOCK' },
    { char = '░', digraph = '.S', name = 'LIGHT SHADE' },
    { char = '▒', digraph = ':S', name = 'MEDIUM SHADE' },
    { char = '▓', digraph = '?S', name = 'DARK SHADE' },
    { char = '■', digraph = 'fS', name = 'BLACK SQUARE' },
    { char = '□', digraph = 'OS', name = 'WHITE SQUARE' },
    { char = '▢', digraph = 'RO', name = 'WHITE SQUARE WITH ROUNDED CORNERS' },
    { char = '▣', digraph = 'Rr', name = 'WHITE SQUARE CONTAINING BLACK SMALL SQUARE' },
    { char = '▤', digraph = 'RF', name = 'SQUARE WITH HORIZONTAL FILL' },
    { char = '▥', digraph = 'RY', name = 'SQUARE WITH VERTICAL FILL' },
    { char = '▦', digraph = 'RH', name = 'SQUARE WITH ORTHOGONAL CROSSHATCH FILL' },
    { char = '▧', digraph = 'RZ', name = 'SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL' },
    { char = '▨', digraph = 'RK', name = 'SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL' },
    { char = '▩', digraph = 'RX', name = 'SQUARE WITH DIAGONAL CROSSHATCH FILL' },
    { char = '▪', digraph = 'sB', name = 'BLACK SMALL SQUARE' },
    { char = '▬', digraph = 'SR', name = 'BLACK RECTANGLE' },
    { char = '▭', digraph = 'Or', name = 'WHITE RECTANGLE' },
    { char = '▲', digraph = 'UT', name = 'BLACK UP-POINTING TRIANGLE' },
    { char = '△', digraph = 'uT', name = 'WHITE UP-POINTING TRIANGLE' },
    { char = '▶', digraph = 'PR', name = 'BLACK RIGHT-POINTING TRIANGLE' },
    { char = '▷', digraph = 'Tr', name = 'WHITE RIGHT-POINTING TRIANGLE' },
    { char = '▼', digraph = 'Dt', name = 'BLACK DOWN-POINTING TRIANGLE' },
    { char = '▽', digraph = 'dT', name = 'WHITE DOWN-POINTING TRIANGLE' },
    { char = '◀', digraph = 'PL', name = 'BLACK LEFT-POINTING TRIANGLE' },
    { char = '◁', digraph = 'Tl', name = 'WHITE LEFT-POINTING TRIANGLE' },
    { char = '◆', digraph = 'Db', name = 'BLACK DIAMOND' },
    { char = '◇', digraph = 'Dw', name = 'WHITE DIAMOND' },
    { char = '◊', digraph = 'LZ', name = 'LOZENGE' },
    { char = '○', digraph = '0m', name = 'WHITE CIRCLE' },
    { char = '◎', digraph = '0o', name = 'BULLSEYE' },
    { char = '●', digraph = '0M', name = 'BLACK CIRCLE' },
    { char = '◐', digraph = '0L', name = 'CIRCLE WITH LEFT HALF BLACK' },
    { char = '◑', digraph = '0R', name = 'CIRCLE WITH RIGHT HALF BLACK' },
    { char = '◘', digraph = 'Sn', name = 'INVERSE BULLET' },
    { char = '◙', digraph = 'Ic', name = 'INVERSE WHITE CIRCLE' },
    { char = '◢', digraph = 'Fd', name = 'BLACK LOWER RIGHT TRIANGLE' },
    { char = '◣', digraph = 'Bd', name = 'BLACK LOWER LEFT TRIANGLE' },
    { char = '★', digraph = '*2', name = 'BLACK STAR' },
    { char = '☆', digraph = '*1', name = 'WHITE STAR' },
    { char = '☜', digraph = '<H', name = 'WHITE LEFT POINTING INDEX' },
    { char = '☞', digraph = '>H', name = 'WHITE RIGHT POINTING INDEX' },
    { char = '☺', digraph = '0u', name = 'WHITE SMILING FACE' },
    { char = '☻', digraph = '0U', name = 'BLACK SMILING FACE' },
    { char = '☼', digraph = 'SU', name = 'WHITE SUN WITH RAYS' },
    { char = '♀', digraph = 'Fm', name = 'FEMALE SIGN' },
    { char = '♂', digraph = 'Ml', name = 'MALE SIGN' },
    { char = '♠', digraph = 'cS', name = 'BLACK SPADE SUIT' },
    { char = '♡', digraph = 'cH', name = 'WHITE HEART SUIT' },
    { char = '♢', digraph = 'cD', name = 'WHITE DIAMOND SUIT' },
    { char = '♣', digraph = 'cC', name = 'BLACK CLUB SUIT' },
    { char = '♩', digraph = 'Md', name = 'QUARTER NOTE `' },
    { char = '♪', digraph = 'M8', name = 'EIGHTH NOTE `' },
    { char = '♫', digraph = 'M2', name = 'BEAMED EIGHTH NOTES' },
    { char = '♭', digraph = 'Mb', name = 'MUSIC FLAT SIGN' },
    { char = '♮', digraph = 'Mx', name = 'MUSIC NATURAL SIGN' },
    { char = '♯', digraph = 'MX', name = 'MUSIC SHARP SIGN' },
    { char = '✓', digraph = 'OK', name = 'CHECK MARK' },
    { char = '✗', digraph = 'XX', name = 'BALLOT X' },
    { char = '✠', digraph = '-X', name = 'MALTESE CROSS' },
    { char = ' ', digraph = 'NS', name = 'NO-BREAK SPACE' },
    { char = '　', digraph = 'IS', name = 'IDEOGRAPHIC SPACE' },
    { char = '、', digraph = ',_', name = 'IDEOGRAPHIC COMMA' },
    { char = '。', digraph = '._', name = 'IDEOGRAPHIC FULL STOP' },
    { char = '〃', digraph = '+"', name = 'DITTO MARK' },
    { char = '〄', digraph = '+_', name = 'JAPANESE INDUSTRIAL STANDARD SYMBOL' },
    { char = '々', digraph = '*_', name = 'IDEOGRAPHIC ITERATION MARK' },
    { char = '〆', digraph = ';_', name = 'IDEOGRAPHIC CLOSING MARK' },
    { char = '〇', digraph = '0_', name = 'IDEOGRAPHIC NUMBER ZERO' },
    { char = '《', digraph = '<+', name = 'LEFT DOUBLE ANGLE BRACKET' },
    { char = '》', digraph = '>+', name = 'RIGHT DOUBLE ANGLE BRACKET' },
    { char = '「', digraph = '<\'', name = 'LEFT CORNER BRACKET' },
    { char = '」', digraph = '>\'', name = 'RIGHT CORNER BRACKET' },
    { char = '『', digraph = '<"', name = 'LEFT WHITE CORNER BRACKET' },
    { char = '』', digraph = '>"', name = 'RIGHT WHITE CORNER BRACKET' },
    { char = '【', digraph = '("', name = 'LEFT BLACK LENTICULAR BRACKET' },
    { char = '】', digraph = ')"', name = 'RIGHT BLACK LENTICULAR BRACKET' },
    { char = '〒', digraph = '=T', name = 'POSTAL MARK' },
    { char = '〓', digraph = '=_', name = 'GETA MARK' },
    { char = '〔', digraph = '(\'', name = 'LEFT TORTOISE SHELL BRACKET' },
    { char = '〕', digraph = ')\'', name = 'RIGHT TORTOISE SHELL BRACKET' },
    { char = '〖', digraph = '(I', name = 'LEFT WHITE LENTICULAR BRACKET' },
    { char = '〗', digraph = ')I', name = 'RIGHT WHITE LENTICULAR BRACKET' },
    { char = '〜', digraph = '-?', name = 'WAVE DASH' },
    { char = 'ぁ', digraph = 'A5', name = 'HIRAGANA LETTER SMALL A' },
    { char = 'あ', digraph = 'a5', name = 'HIRAGANA LETTER A' },
    { char = 'ぃ', digraph = 'I5', name = 'HIRAGANA LETTER SMALL I' },
    { char = 'い', digraph = 'i5', name = 'HIRAGANA LETTER I' },
    { char = 'ぅ', digraph = 'U5', name = 'HIRAGANA LETTER SMALL U' },
    { char = 'う', digraph = 'u5', name = 'HIRAGANA LETTER U' },
    { char = 'ぇ', digraph = 'E5', name = 'HIRAGANA LETTER SMALL E' },
    { char = 'え', digraph = 'e5', name = 'HIRAGANA LETTER E' },
    { char = 'ぉ', digraph = 'O5', name = 'HIRAGANA LETTER SMALL O' },
    { char = 'お', digraph = 'o5', name = 'HIRAGANA LETTER O' },
    { char = 'か', digraph = 'ka', name = 'HIRAGANA LETTER KA' },
    { char = 'が', digraph = 'ga', name = 'HIRAGANA LETTER GA' },
    { char = 'き', digraph = 'ki', name = 'HIRAGANA LETTER KI' },
    { char = 'ぎ', digraph = 'gi', name = 'HIRAGANA LETTER GI' },
    { char = 'く', digraph = 'ku', name = 'HIRAGANA LETTER KU' },
    { char = 'ぐ', digraph = 'gu', name = 'HIRAGANA LETTER GU' },
    { char = 'け', digraph = 'ke', name = 'HIRAGANA LETTER KE' },
    { char = 'げ', digraph = 'ge', name = 'HIRAGANA LETTER GE' },
    { char = 'こ', digraph = 'ko', name = 'HIRAGANA LETTER KO' },
    { char = 'ご', digraph = 'go', name = 'HIRAGANA LETTER GO' },
    { char = 'さ', digraph = 'sa', name = 'HIRAGANA LETTER SA' },
    { char = 'ざ', digraph = 'za', name = 'HIRAGANA LETTER ZA' },
    { char = 'し', digraph = 'si', name = 'HIRAGANA LETTER SI' },
    { char = 'じ', digraph = 'zi', name = 'HIRAGANA LETTER ZI' },
    { char = 'す', digraph = 'su', name = 'HIRAGANA LETTER SU' },
    { char = 'ず', digraph = 'zu', name = 'HIRAGANA LETTER ZU' },
    { char = 'せ', digraph = 'se', name = 'HIRAGANA LETTER SE' },
    { char = 'ぜ', digraph = 'ze', name = 'HIRAGANA LETTER ZE' },
    { char = 'そ', digraph = 'so', name = 'HIRAGANA LETTER SO' },
    { char = 'ぞ', digraph = 'zo', name = 'HIRAGANA LETTER ZO' },
    { char = 'た', digraph = 'ta', name = 'HIRAGANA LETTER TA' },
    { char = 'だ', digraph = 'da', name = 'HIRAGANA LETTER DA' },
    { char = 'ち', digraph = 'ti', name = 'HIRAGANA LETTER TI' },
    { char = 'ぢ', digraph = 'di', name = 'HIRAGANA LETTER DI' },
    { char = 'っ', digraph = 'tU', name = 'HIRAGANA LETTER SMALL TU' },
    { char = 'つ', digraph = 'tu', name = 'HIRAGANA LETTER TU' },
    { char = 'づ', digraph = 'du', name = 'HIRAGANA LETTER DU' },
    { char = 'て', digraph = 'te', name = 'HIRAGANA LETTER TE' },
    { char = 'で', digraph = 'de', name = 'HIRAGANA LETTER DE' },
    { char = 'と', digraph = 'to', name = 'HIRAGANA LETTER TO' },
    { char = 'ど', digraph = 'do', name = 'HIRAGANA LETTER DO' },
    { char = 'な', digraph = 'na', name = 'HIRAGANA LETTER NA' },
    { char = 'に', digraph = 'ni', name = 'HIRAGANA LETTER NI' },
    { char = 'ぬ', digraph = 'nu', name = 'HIRAGANA LETTER NU' },
    { char = 'ね', digraph = 'ne', name = 'HIRAGANA LETTER NE' },
    { char = 'の', digraph = 'no', name = 'HIRAGANA LETTER NO' },
    { char = 'は', digraph = 'ha', name = 'HIRAGANA LETTER HA' },
    { char = 'ば', digraph = 'ba', name = 'HIRAGANA LETTER BA' },
    { char = 'ぱ', digraph = 'pa', name = 'HIRAGANA LETTER PA' },
    { char = 'ひ', digraph = 'hi', name = 'HIRAGANA LETTER HI' },
    { char = 'び', digraph = 'bi', name = 'HIRAGANA LETTER BI' },
    { char = 'ぴ', digraph = 'pi', name = 'HIRAGANA LETTER PI' },
    { char = 'ふ', digraph = 'hu', name = 'HIRAGANA LETTER HU' },
    { char = 'ぶ', digraph = 'bu', name = 'HIRAGANA LETTER BU' },
    { char = 'ぷ', digraph = 'pu', name = 'HIRAGANA LETTER PU' },
    { char = 'へ', digraph = 'he', name = 'HIRAGANA LETTER HE' },
    { char = 'べ', digraph = 'be', name = 'HIRAGANA LETTER BE' },
    { char = 'ぺ', digraph = 'pe', name = 'HIRAGANA LETTER PE' },
    { char = 'ほ', digraph = 'ho', name = 'HIRAGANA LETTER HO' },
    { char = 'ぼ', digraph = 'bo', name = 'HIRAGANA LETTER BO' },
    { char = 'ぽ', digraph = 'po', name = 'HIRAGANA LETTER PO' },
    { char = 'ま', digraph = 'ma', name = 'HIRAGANA LETTER MA' },
    { char = 'み', digraph = 'mi', name = 'HIRAGANA LETTER MI' },
    { char = 'む', digraph = 'mu', name = 'HIRAGANA LETTER MU' },
    { char = 'め', digraph = 'me', name = 'HIRAGANA LETTER ME' },
    { char = 'も', digraph = 'mo', name = 'HIRAGANA LETTER MO' },
    { char = 'ゃ', digraph = 'yA', name = 'HIRAGANA LETTER SMALL YA' },
    { char = 'や', digraph = 'ya', name = 'HIRAGANA LETTER YA' },
    { char = 'ゅ', digraph = 'yU', name = 'HIRAGANA LETTER SMALL YU' },
    { char = 'ゆ', digraph = 'yu', name = 'HIRAGANA LETTER YU' },
    { char = 'ょ', digraph = 'yO', name = 'HIRAGANA LETTER SMALL YO' },
    { char = 'よ', digraph = 'yo', name = 'HIRAGANA LETTER YO' },
    { char = 'ら', digraph = 'ra', name = 'HIRAGANA LETTER RA' },
    { char = 'り', digraph = 'ri', name = 'HIRAGANA LETTER RI' },
    { char = 'る', digraph = 'ru', name = 'HIRAGANA LETTER RU' },
    { char = 'れ', digraph = 're', name = 'HIRAGANA LETTER RE' },
    { char = 'ろ', digraph = 'ro', name = 'HIRAGANA LETTER RO' },
    { char = 'ゎ', digraph = 'wA', name = 'HIRAGANA LETTER SMALL WA' },
    { char = 'わ', digraph = 'wa', name = 'HIRAGANA LETTER WA' },
    { char = 'ゐ', digraph = 'wi', name = 'HIRAGANA LETTER WI' },
    { char = 'ゑ', digraph = 'we', name = 'HIRAGANA LETTER WE' },
    { char = 'を', digraph = 'wo', name = 'HIRAGANA LETTER WO' },
    { char = 'ん', digraph = 'n5', name = 'HIRAGANA LETTER N `' },
    { char = 'ゔ', digraph = 'vu', name = 'HIRAGANA LETTER VU' },
    { char = '゛', digraph = '"5', name = 'KATAKANA-HIRAGANA VOICED SOUND MARK' },
    { char = '゜', digraph = '05', name = 'KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK' },
    { char = 'ゝ', digraph = '*5', name = 'HIRAGANA ITERATION MARK' },
    { char = 'ゞ', digraph = '+5', name = 'HIRAGANA VOICED ITERATION MARK' },
    { char = 'ァ', digraph = 'a6', name = 'KATAKANA LETTER SMALL A' },
    { char = 'ア', digraph = 'A6', name = 'KATAKANA LETTER A' },
    { char = 'ィ', digraph = 'i6', name = 'KATAKANA LETTER SMALL I' },
    { char = 'イ', digraph = 'I6', name = 'KATAKANA LETTER I' },
    { char = 'ゥ', digraph = 'u6', name = 'KATAKANA LETTER SMALL U' },
    { char = 'ウ', digraph = 'U6', name = 'KATAKANA LETTER U' },
    { char = 'ェ', digraph = 'e6', name = 'KATAKANA LETTER SMALL E' },
    { char = 'エ', digraph = 'E6', name = 'KATAKANA LETTER E' },
    { char = 'ォ', digraph = 'o6', name = 'KATAKANA LETTER SMALL O' },
    { char = 'オ', digraph = 'O6', name = 'KATAKANA LETTER O' },
    { char = 'カ', digraph = 'Ka', name = 'KATAKANA LETTER KA' },
    { char = 'ガ', digraph = 'Ga', name = 'KATAKANA LETTER GA' },
    { char = 'キ', digraph = 'Ki', name = 'KATAKANA LETTER KI' },
    { char = 'ギ', digraph = 'Gi', name = 'KATAKANA LETTER GI' },
    { char = 'ク', digraph = 'Ku', name = 'KATAKANA LETTER KU' },
    { char = 'グ', digraph = 'Gu', name = 'KATAKANA LETTER GU' },
    { char = 'ケ', digraph = 'Ke', name = 'KATAKANA LETTER KE' },
    { char = 'ゲ', digraph = 'Ge', name = 'KATAKANA LETTER GE' },
    { char = 'コ', digraph = 'Ko', name = 'KATAKANA LETTER KO' },
    { char = 'ゴ', digraph = 'Go', name = 'KATAKANA LETTER GO' },
    { char = 'サ', digraph = 'Sa', name = 'KATAKANA LETTER SA' },
    { char = 'ザ', digraph = 'Za', name = 'KATAKANA LETTER ZA' },
    { char = 'シ', digraph = 'Si', name = 'KATAKANA LETTER SI' },
    { char = 'ジ', digraph = 'Zi', name = 'KATAKANA LETTER ZI' },
    { char = 'ス', digraph = 'Su', name = 'KATAKANA LETTER SU' },
    { char = 'ズ', digraph = 'Zu', name = 'KATAKANA LETTER ZU' },
    { char = 'セ', digraph = 'Se', name = 'KATAKANA LETTER SE' },
    { char = 'ゼ', digraph = 'Ze', name = 'KATAKANA LETTER ZE' },
    { char = 'ソ', digraph = 'So', name = 'KATAKANA LETTER SO' },
    { char = 'ゾ', digraph = 'Zo', name = 'KATAKANA LETTER ZO' },
    { char = 'タ', digraph = 'Ta', name = 'KATAKANA LETTER TA' },
    { char = 'ダ', digraph = 'Da', name = 'KATAKANA LETTER DA' },
    { char = 'チ', digraph = 'Ti', name = 'KATAKANA LETTER TI' },
    { char = 'ヂ', digraph = 'Di', name = 'KATAKANA LETTER DI' },
    { char = 'ッ', digraph = 'TU', name = 'KATAKANA LETTER SMALL TU' },
    { char = 'ツ', digraph = 'Tu', name = 'KATAKANA LETTER TU' },
    { char = 'ヅ', digraph = 'Du', name = 'KATAKANA LETTER DU' },
    { char = 'テ', digraph = 'Te', name = 'KATAKANA LETTER TE' },
    { char = 'デ', digraph = 'De', name = 'KATAKANA LETTER DE' },
    { char = 'ト', digraph = 'To', name = 'KATAKANA LETTER TO' },
    { char = 'ド', digraph = 'Do', name = 'KATAKANA LETTER DO' },
    { char = 'ナ', digraph = 'Na', name = 'KATAKANA LETTER NA' },
    { char = 'ニ', digraph = 'Ni', name = 'KATAKANA LETTER NI' },
    { char = 'ヌ', digraph = 'Nu', name = 'KATAKANA LETTER NU' },
    { char = 'ネ', digraph = 'Ne', name = 'KATAKANA LETTER NE' },
    { char = 'ノ', digraph = 'No', name = 'KATAKANA LETTER NO' },
    { char = 'ハ', digraph = 'Ha', name = 'KATAKANA LETTER HA' },
    { char = 'バ', digraph = 'Ba', name = 'KATAKANA LETTER BA' },
    { char = 'パ', digraph = 'Pa', name = 'KATAKANA LETTER PA' },
    { char = 'ヒ', digraph = 'Hi', name = 'KATAKANA LETTER HI' },
    { char = 'ビ', digraph = 'Bi', name = 'KATAKANA LETTER BI' },
    { char = 'ピ', digraph = 'Pi', name = 'KATAKANA LETTER PI' },
    { char = 'フ', digraph = 'Hu', name = 'KATAKANA LETTER HU' },
    { char = 'ブ', digraph = 'Bu', name = 'KATAKANA LETTER BU' },
    { char = 'プ', digraph = 'Pu', name = 'KATAKANA LETTER PU' },
    { char = 'ヘ', digraph = 'He', name = 'KATAKANA LETTER HE' },
    { char = 'ベ', digraph = 'Be', name = 'KATAKANA LETTER BE' },
    { char = 'ペ', digraph = 'Pe', name = 'KATAKANA LETTER PE' },
    { char = 'ホ', digraph = 'Ho', name = 'KATAKANA LETTER HO' },
    { char = 'ボ', digraph = 'Bo', name = 'KATAKANA LETTER BO' },
    { char = 'ポ', digraph = 'Po', name = 'KATAKANA LETTER PO' },
    { char = 'マ', digraph = 'Ma', name = 'KATAKANA LETTER MA' },
    { char = 'ミ', digraph = 'Mi', name = 'KATAKANA LETTER MI' },
    { char = 'ム', digraph = 'Mu', name = 'KATAKANA LETTER MU' },
    { char = 'メ', digraph = 'Me', name = 'KATAKANA LETTER ME' },
    { char = 'モ', digraph = 'Mo', name = 'KATAKANA LETTER MO' },
    { char = 'ャ', digraph = 'YA', name = 'KATAKANA LETTER SMALL YA' },
    { char = 'ヤ', digraph = 'Ya', name = 'KATAKANA LETTER YA' },
    { char = 'ュ', digraph = 'YU', name = 'KATAKANA LETTER SMALL YU' },
    { char = 'ユ', digraph = 'Yu', name = 'KATAKANA LETTER YU' },
    { char = 'ョ', digraph = 'YO', name = 'KATAKANA LETTER SMALL YO' },
    { char = 'ヨ', digraph = 'Yo', name = 'KATAKANA LETTER YO' },
    { char = 'ラ', digraph = 'Ra', name = 'KATAKANA LETTER RA' },
    { char = 'リ', digraph = 'Ri', name = 'KATAKANA LETTER RI' },
    { char = 'ル', digraph = 'Ru', name = 'KATAKANA LETTER RU' },
    { char = 'レ', digraph = 'Re', name = 'KATAKANA LETTER RE' },
    { char = 'ロ', digraph = 'Ro', name = 'KATAKANA LETTER RO' },
    { char = 'ヮ', digraph = 'WA', name = 'KATAKANA LETTER SMALL WA' },
    { char = 'ワ', digraph = 'Wa', name = 'KATAKANA LETTER WA' },
    { char = 'ヰ', digraph = 'Wi', name = 'KATAKANA LETTER WI' },
    { char = 'ヱ', digraph = 'We', name = 'KATAKANA LETTER WE' },
    { char = 'ヲ', digraph = 'Wo', name = 'KATAKANA LETTER WO' },
    { char = 'ン', digraph = 'N6', name = 'KATAKANA LETTER N `' },
    { char = 'ヴ', digraph = 'Vu', name = 'KATAKANA LETTER VU' },
    { char = 'ヵ', digraph = 'KA', name = 'KATAKANA LETTER SMALL KA' },
    { char = 'ヶ', digraph = 'KE', name = 'KATAKANA LETTER SMALL KE' },
    { char = 'ヷ', digraph = 'Va', name = 'KATAKANA LETTER VA' },
    { char = 'ヸ', digraph = 'Vi', name = 'KATAKANA LETTER VI' },
    { char = 'ヹ', digraph = 'Ve', name = 'KATAKANA LETTER VE' },
    { char = 'ヺ', digraph = 'Vo', name = 'KATAKANA LETTER VO' },
    { char = '・', digraph = '.6', name = 'KATAKANA MIDDLE DOT' },
    { char = 'ー', digraph = '-6', name = 'KATAKANA-HIRAGANA PROLONGED SOUND MARK' },
    { char = 'ヽ', digraph = '*6', name = 'KATAKANA ITERATION MARK' },
    { char = 'ヾ', digraph = '+6', name = 'KATAKANA VOICED ITERATION MARK' },
    { char = 'ㄅ', digraph = 'b4', name = 'BOPOMOFO LETTER B' },
    { char = 'ㄆ', digraph = 'p4', name = 'BOPOMOFO LETTER P' },
    { char = 'ㄇ', digraph = 'm4', name = 'BOPOMOFO LETTER M' },
    { char = 'ㄈ', digraph = 'f4', name = 'BOPOMOFO LETTER F' },
    { char = 'ㄉ', digraph = 'd4', name = 'BOPOMOFO LETTER D' },
    { char = 'ㄊ', digraph = 't4', name = 'BOPOMOFO LETTER T' },
    { char = 'ㄋ', digraph = 'n4', name = 'BOPOMOFO LETTER N `' },
    { char = 'ㄌ', digraph = 'l4', name = 'BOPOMOFO LETTER L' },
    { char = 'ㄍ', digraph = 'g4', name = 'BOPOMOFO LETTER G' },
    { char = 'ㄎ', digraph = 'k4', name = 'BOPOMOFO LETTER K' },
    { char = 'ㄏ', digraph = 'h4', name = 'BOPOMOFO LETTER H' },
    { char = 'ㄐ', digraph = 'j4', name = 'BOPOMOFO LETTER J' },
    { char = 'ㄑ', digraph = 'q4', name = 'BOPOMOFO LETTER Q' },
    { char = 'ㄒ', digraph = 'x4', name = 'BOPOMOFO LETTER X' },
    { char = 'ㄓ', digraph = 'zh', name = 'BOPOMOFO LETTER ZH' },
    { char = 'ㄔ', digraph = 'ch', name = 'BOPOMOFO LETTER CH' },
    { char = 'ㄕ', digraph = 'sh', name = 'BOPOMOFO LETTER SH' },
    { char = 'ㄖ', digraph = 'r4', name = 'BOPOMOFO LETTER R' },
    { char = 'ㄗ', digraph = 'z4', name = 'BOPOMOFO LETTER Z' },
    { char = 'ㄘ', digraph = 'c4', name = 'BOPOMOFO LETTER C' },
    { char = 'ㄙ', digraph = 's4', name = 'BOPOMOFO LETTER S' },
    { char = 'ㄚ', digraph = 'a4', name = 'BOPOMOFO LETTER A' },
    { char = 'ㄛ', digraph = 'o4', name = 'BOPOMOFO LETTER O' },
    { char = 'ㄜ', digraph = 'e4', name = 'BOPOMOFO LETTER E' },
    { char = 'ㄞ', digraph = 'ai', name = 'BOPOMOFO LETTER AI' },
    { char = 'ㄟ', digraph = 'ei', name = 'BOPOMOFO LETTER EI' },
    { char = 'ㄠ', digraph = 'au', name = 'BOPOMOFO LETTER AU' },
    { char = 'ㄡ', digraph = 'ou', name = 'BOPOMOFO LETTER OU' },
    { char = 'ㄢ', digraph = 'an', name = 'BOPOMOFO LETTER AN' },
    { char = 'ㄣ', digraph = 'en', name = 'BOPOMOFO LETTER EN' },
    { char = 'ㄤ', digraph = 'aN', name = 'BOPOMOFO LETTER ANG' },
    { char = 'ㄥ', digraph = 'eN', name = 'BOPOMOFO LETTER ENG' },
    { char = 'ㄦ', digraph = 'er', name = 'BOPOMOFO LETTER ER' },
    { char = 'ㄧ', digraph = 'i4', name = 'BOPOMOFO LETTER I' },
    { char = 'ㄨ', digraph = 'u4', name = 'BOPOMOFO LETTER U' },
    { char = 'ㄩ', digraph = 'iu', name = 'BOPOMOFO LETTER IU' },
    { char = 'ㄪ', digraph = 'v4', name = 'BOPOMOFO LETTER V' },
    { char = 'ㄫ', digraph = 'nG', name = 'BOPOMOFO LETTER NG' },
    { char = 'ㄬ', digraph = 'gn', name = 'BOPOMOFO LETTER GN' },
    { char = '㈠', digraph = '1c', name = 'PARENTHESIZED IDEOGRAPH ONE' },
    { char = '㈡', digraph = '2c', name = 'PARENTHESIZED IDEOGRAPH TWO' },
    { char = '㈢', digraph = '3c', name = 'PARENTHESIZED IDEOGRAPH THREE' },
    { char = '㈣', digraph = '4c', name = 'PARENTHESIZED IDEOGRAPH FOUR' },
    { char = '㈤', digraph = '5c', name = 'PARENTHESIZED IDEOGRAPH FIVE' },
    { char = '㈥', digraph = '6c', name = 'PARENTHESIZED IDEOGRAPH SIX' },
    { char = '㈦', digraph = '7c', name = 'PARENTHESIZED IDEOGRAPH SEVEN' },
    { char = '㈧', digraph = '8c', name = 'PARENTHESIZED IDEOGRAPH EIGHT' },
    { char = '㈨', digraph = '9c', name = 'PARENTHESIZED IDEOGRAPH NINE' },
    { char = 'ﬀ', digraph = 'ff', name = 'LATIN SMALL LIGATURE FF' },
    { char = 'ﬁ', digraph = 'fi', name = 'LATIN SMALL LIGATURE FI' },
    { char = 'ﬂ', digraph = 'fl', name = 'LATIN SMALL LIGATURE FL' },
    { char = 'ﬅ', digraph = 'ft', name = 'LATIN SMALL LIGATURE LONG S T' },
    { char = 'ﬆ', digraph = 'st', name = 'LATIN SMALL LIGATURE ST' },
  },
}
